### ISSUE TITLE
[Question]: How to make dockerized windows not reinstall

### ISSUE THREAD

**Issue by FrozenGamesYT** [dockur/windows#1004]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

How to make dockerized windows not reinstall when i turn it off and back on?

**Comment by FrozenGamesYT** [comment]
My compose file:

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DHCP: "Y"
    devices:
      - /dev/vhost-net
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    device_cgroup_rules:
      - 'c *:* rwm'
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

    networks:
      Windows:
        mac_address: "52:54:00:BB:ED:72"
        ipv4_address: 10.0.0.9

networks:
  Windows:
    external: true
```
