### ISSUE TITLE
install.bat doesn't run after manual installation of windows server core

### ISSUE THREAD

**Issue by sirzento** [dockur/windows#1031]
### Operating system

Windows 11 host and Windows Server 2025 Core inside docker

### Description

The install.bat file doesn't get executed after installing. Inside the oem directory are `install.bat` and `test.txt`. 
Inside the `install.bat` is just a `copy C:\\oem\test.txt C:\\oem\test2.txt` to see if the file gets executed.

After installation, when looking inside the oem folder, there wont be a `test2.txt` file. Other commands inside install.bat won't get executed.
I can run the install.bat myself without problems via cmd at `C:\\oem\install.bat`

### Docker compose

```
services:
    windows:
        image: dockurr/windows
        container_name: windows_test
        environment:
            MANUAL: "Y"
        devices:
            - /dev/kvm
            - /dev/net/tun
        cap_add:
            - NET_ADMIN
        ports:
            - 3007:3000
            - 8014:8006
        stop_grace_period: 2m
        volumes:
            - C:\Users\Sirzento\Desktop\Docker\shared:/data
            - C:\Users\Sirzento\Desktop\Docker\oem:/oem
            - C:\Users\Sirzento\Desktop\Docker\win-server-2025.iso:/custom.iso
```

### Docker log

Can't really get usefull logs here. Its just two lines from boot manager.
