### ISSUE TITLE
Fail to install: Windows installer error (0x8007025D)

### ISSUE THREAD

**Issue by StackGoblin** [dockur/windows#1034]
### Operating system

Arch/EndeavorOS

### Description

I'm trying to install this through [https://github.com/winapps-org/winapps](url) to run some adobe products I need for a project. However the install is consistently failing regardless of version I use. My root directory, which based on their documentation this wants to install the vm into, is btrfs and only has 50G of storage (I keep my /home folder on a different partition). 

The failure seems to be on the part of the windows installer itself, which I don't know if it is connected to my filesystem format or lack of storage space. If anyone has any advice on how to configure this compose file for my use case it is appreciated. I do have room on a second hard drive where I can create a separate partition to install and run this vm from if that can help resolve this issue.

### Docker compose

```bash
# For documentation, FAQ, additional configuration options and technical help, visit: https://github.com/dockur/windows

name: "winapps" # Docker Compose Project Name.
volumes:
  # Create Volume 'data'.
  # Located @ '/var/lib/docker/volumes/winapps_data/_data' (Docker).
  # Located @ '/var/lib/containers/storage/volumes/winapps_data/_data' or '~/.local/share/containers/storage/volumes/winapps_data/_data' (Podman).
  data:
services:
  windows:
    image: ghcr.io/dockur/windows:latest
    container_name: WinApps # Created Docker VM Name.
    environment:
      # Version of Windows to configure. For valid options, visit:
      # https://github.com/dockur/windows?tab=readme-ov-file#how-do-i-select-the-windows-version
      # https://github.com/dockur/windows?tab=readme-ov-file#how-do-i-install-a-custom-image
      VERSION: "tiny11"
      RAM_SIZE: "4G" # RAM allocated to the Windows VM.
      CPU_CORES: "4" # CPU cores allocated to the Windows VM.
      DISK_SIZE: "64G" # Size of the primary hard disk.
      #DISK2_SIZE: "32G" # Uncomment to add an additional hard disk to the Windows VM. Ensure it is mounted as a volume below.
      USERNAME: "MyWindowsUser" # Edit here to set a custom Windows username. The default is 'MyWindowsUser'.
      PASSWORD: "MyWindowsPassword" # Edit here to set a password for the Windows user. The default is 'MyWindowsPassword'.
      HOME: "${HOME}" # Set path to Linux user home folder.
    privileged: true # Grant the Windows VM extended privileges.
    ports:
      - 8006:8006 # Map '8006' on Linux host to '8006' on Windows VM --> For VNC Web Interface @ http://127.0.0.1:8006.
      - 3389:3389/tcp # Map '3389' on Linux host to '3389' on Windows VM --> For Remote Desktop Protocol (RDP).
      - 3389:3389/udp # Map '3389' on Linux host to '3389' on Windows VM --> For Remote Desktop Protocol (RDP).
    stop_grace_period: 120s # Wait 120 seconds before sending SIGTERM when attempting to shut down the Windows VM.
    restart: on-failure # Restart the Windows VM if the exit code indicates an error.
    volumes:
      - data:/storage # Mount volume 'data' to use as Windows 'C:' drive.
      - ${HOME}:/shared # Mount Linux user home directory @ '\\host.lan\Data'.
      #- /path/to/second/hard/disk:/storage2 # Uncomment to mount the second hard disk within the Windows VM. Ensure 'DISK2_SIZE' is specified above.
      - ./oem:/oem # Enables automatic post-install execution of 'oem/install.bat', applying Windows registry modifications contained within 'oem/RDPApps.reg'.
      #- /path/to/windows/install/media.iso:/custom.iso # Uncomment to use a custom Windows ISO. If specified, 'VERSION' (e.g. 'tiny11') will be ignored.
    devices:
      - /dev/kvm # Enable KVM.
      #- /dev/sdX:/disk1 # Uncomment to mount a disk directly within the Windows VM (Note: 'disk1' will be mounted as the main drive. THIS DISK WILL BE FORMATTED BY DOCKER).
      #- /dev/sdY:/disk2 # Uncomment to mount a disk directly within the Windows VM (Note: 'disk2' and higher will be mounted as secondary drives. THIS DISK WILL NOT BE FORMATTED).
```

### Docker log

not available atm. Can provide later if needed.

### Screenshots (optional)

![Image](https://github.com/user-attachments/assets/4bd9ee43-cfcf-456b-b447-780cf5f89687)

**Comment by StackGoblin** [comment]
thanks for the quick reply! How can I configure the file to run in a particular partition? Would that be as simple as mounting the `data` volume to the path for this partition, such as:
```bash
volumes:
      - /path/to/folder/in/partition:/storage
```
What type of file system would you recommend?

**Comment by StackGoblin** [comment]
Ok, I'll give it a try later today and report back if there are still issues.

From the documentation in this section my understanding is that the volume `data` is being created in the root directory by default
```bash
volumes:
  # Create Volume 'data'.
  # Located @ '/var/lib/docker/volumes/winapps_data/_data' (Docker).
  # Located @ '/var/lib/containers/storage/volumes/winapps_data/_data' or '~/.local/share/containers/storage/volumes/winapps_data/_data' (Podman).
  data:
```
Or am I incorrect and for my use case I could remove this section of the file?

**Comment by StackGoblin** [comment]
I tried to modify the compose file however I'm now getting the following error.

```bash
WinApps  | ❯ CPU: AMD Ryzen 9 5900X 12 Core | RAM: 25/32 GB | DISK: 90 GB (msdos) | KERNEL: 6.13.2-arch1-1...
WinApps  | 
WinApps  | ❯ Creating a 64G growable disk image in raw format...
WinApps  | truncate: failed to truncate '/storage/data.img' at 68719476736 bytes: File too large
WinApps  | ❯ ERROR: Could not create a growable raw disk image of 64G (/storage/data.img)
```

## Compose File
```yaml
name: "winapps" # Docker Compose Project Name.
services:
  windows:
    image: ghcr.io/dockur/windows:latest
    container_name: WinApps # Created Docker VM Name.
    environment:
      VERSION: "tiny10"
      RAM_SIZE: "8G" # RAM allocated to the Windows VM.
      CPU_CORES: "8" # CPU cores allocated to the Windows VM.
      DISK_SIZE: "64G" # Size of the primary hard disk.
      USERNAME: "MyWindowsUser" 
      PASSWORD: "MyWindowsPassword"
      HOME: "${HOME}" 
    privileged: true 
    ports:
      - 8006:8006
      - 3389:3389/tcp 
      - 3389:3389/udp 
    stop_grace_period: 120s
    restart: on-failure
    volumes:
      - /home/user/drives/WindowsVM:/storage
      - ${HOME}:/shared 
      - ./oem:/oem # Enables automatic post-install execution of 'oem/install.bat', applying Windows registry modifications contained within 'oem/RDPApps.reg'.
    devices:
      - /dev/kvm
```
