### ISSUE TITLE
ACPI shutdown signal isn't causing Windows to shutdown

### ISSUE THREAD

**Issue by profucius** [dockur/windows#1043]
### Operating system

Proxmox > Debian 12 LXC > Portainer

### Description

Just noticed when I was editing my docker compose and applying it (in Portainer) that the logs state it sent a "ACPI shutdown signal" and then waits for 2 minutes (timeout set in compose). When I remote into Windows, nothing seems to have changed, it isn't attempting to shutdown. When I tell Windows to shutdown manually, then the docker container is able to update and restart automatically. I'd like Windows to shut itself down in this scenario.

Is there something I can take a look at to see why this might be happening, or perhaps something I can do to fix it? I did install the full suite of VirtIO drivers already, no change.

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: unless-stopped
    privileged: true
    environment:
      MANUAL: "Y"
      DISK_SIZE: "20G" # Can expand, but never shrink!
      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net # Enable if using `Network/vlan` method above.
    volumes:
      - /home/rawos/:/storage
      - /home/share:/shared # Found at: Explorer > Network > \\host.lan. Can be mounted as drive too.
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vlan:
        ipv4_address: 192.168.1.128
networks:
  vlan:
    external: true
```

### Docker log

.
