### ISSUE TITLE
Formatting USB device passthrough incorrectly

### ISSUE THREAD

**Issue by NotGreatWithCode** [dockur/windows#1046]
### Operating system

Debian 12 (bookworm)

### Description

I know I'm formatting my docker compose file incorrectly but am unaware of how to format it. 
Assistance would be greatly appreciated.

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "Tiny10"
      ARGUMENTS: "-device usb-host,vendorid=0x1d6b,productid=0x0002"
                 "-device usb-host,vendorid=0x1d6b,productid=0x0003"
                 "-device usb-host,vendorid=0x046d,productid=0x0ab5"
                 "-device usb-host,vendorid=0x0bda,productid=0x8771"
                 "-device usb-host,vendorid=0x0d8c,productid=0x0014"
                 "-device usb-host,vendorid=0x0d8c,productid=0x0102"
                 "-device usb-host,vendorid=0x046d,productid=0x0acb"
                 "-device usb-host,vendorid=0x6666,productid=0x6671"
    volumes:
      - /home/user/windows:/data
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/net/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m

```

### Docker log

Container has not spun up with current configuration.

### Screenshots (optional)

![Image](https://github.com/user-attachments/assets/ccae2171-dc39-4a67-bd01-202a455ec649)

![Image](https://github.com/user-attachments/assets/f6927ae6-32f0-41c5-90f9-757ea44e9051)
