### ISSUE TITLE
[Question]: How can I export the drive to use it in Virt-Manager or VirtualBox ?

### ISSUE THREAD

**Issue by ignaciogutierrez** [dockur/windows#1047]
### Is your question not already answered in the FAQ?

- [x] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [x] I am sure my question is not about a technical issue.

### Question

I use Debian12 as Host OS, and create the container changing the storage location. Works Perfect !

But when I tried to use the drive file: data.qcow2  in virt-manager or virtualbox I got error  **"no bootable device"**

This is my docker-compose.yml

```
services:
  windows:
    image: dockurr/windows
    container_name: win2022
    environment:
      VERSION: "2022"
      DISK_FMT: "qcow2"
      DISK_SIZE: "50G"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      USERNAME: "administrator"
      PASSWORD: "supersecret"
    devices:
      - /dev/kvm
      - /dev/net/tun
    volumes:
      - ./mystorage:/storage
      - ./sharedrv:/data
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3489:3389/tcp
      - 3489:3389/udp
    restart: always
    stop_grace_period: 2m
```

Container was created perfect and runs OK

It creates the folder mystorage with the drive named: data.qcow2
```
-rw-r--r-- 1 root root 9688121344 Feb 18 16:24 data.qcow2
-rw-r--r-- 1 root root         20 Feb 18 12:38 windows.base
-rw-r--r-- 1 root root          0 Feb 18 12:43 windows.boot
-rw-r--r-- 1 root root         18 Feb 18 12:38 windows.mac
-rw-r--r-- 1 root root    3653632 Feb 18 12:38 windows.rom
-rw-r--r-- 1 root root     540672 Feb 18 16:24 windows.vars
-rw-r--r-- 1 root root          5 Feb 18 12:38 windows.ver
```

But if I try to use the file **data.qcow2** on Virtualbox or VirtManager, both aborts with the same error: **"no bootable device"**

Is there any way to export the drive or mark it as bootable, to be used in VirtualBox or VirtManager ?
