### ISSUE TITLE
[Bug]: Can't install dockurr/windows iso

### ISSUE THREAD

**Issue by femto** [dockur/windows#1048]
### Operating system

Mac Sonoma 14.6.1

### Description

I downloaded windows 11 and rename it to setup.iso
remove devices:
      - /dev/kvm
      - /dev/net/tun
and add KVM: "N"

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      KVM: "N"
    volumes:
      - /Users/femtozheng/python-project/WindowsAgentArena/src/win-arena-container/vm/image/setup.iso:/custom.iso
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m
```
but can't install, just shows this, seemed to hang
<img width="1363" alt="Image" src="https://github.com/user-attachments/assets/bdee67f5-c7ad-4007-be6d-17f78b04035b" />

### Docker compose

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      KVM: "N"
    volumes:
      - /Users/femtozheng/python-project/WindowsAgentArena/src/win-arena-container/vm/image/setup.iso:/custom.iso
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    restart: always
    stop_grace_period: 2m

### Docker log

BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

### Screenshots (optional)

<img width="1363" alt="Image" src="https://github.com/user-attachments/assets/bdee67f5-c7ad-4007-be6d-17f78b04035b" />
