### ISSUE TITLE
Adding sound device

### ISSUE THREAD

**Issue by Irishdab** [dockur/windows#108]
Sorry but I am new. How would I add a sound device to the Windows 10 docker?? I know with a VM you add <sound model='ich6'> to the xml config but not sure how to do it in this case. While I know noVNC can't play audio I am looking to use teamviewer to access this remotely.

**Comment by y0utubeperson1** [comment]
@kroese not sure if i can comment on a closed thread but do these arguments need to be put on installation only? For example, if i have a windows container and then put it, would it fail? I have a windows container already and tried both but I get these errors
![image](https://github.com/dockur/windows/assets/23609444/e6642be6-f807-4b1c-90b0-0adac4ed7bbe)
![image](https://github.com/dockur/windows/assets/23609444/d403b82c-8fb0-462f-9530-db3207cb048b)

My docker-compose:
```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "winxp"
      ARGUMENTS: "-device ich9-intel-hda -device hda-output"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
```
