### ISSUE TITLE
Container restarts in a loop

### ISSUE THREAD

**Issue by Didier3L** [dockur/windows#1118]
### Operating system

macos 15.3.2 BuildVersion 24D81

### Description

Container restarts in a loop

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    privileged: true
    environment:
      VERSION: "10"
      USERNAME: "Didier"
      PASSWORD: "claricel"
      LANGUAGE: "French"
      REGION: "fr-FR"
      KEYBOARD: "fr-FR"
      RAM_SIZE: "64G"
      CPU_CORES: "4"
      KVM: "N" # THIS line solved the problem
      RAM_CHECK: "N"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /Users/didier/docker/windows:/storage
      - /Users/didier/docker/windows/data:/data #partager des fichiers avec l'hôte
    restart: always
    stop_grace_period: 2m
```

### Docker log

BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU USB HARDDRIVE 1-0000:00:01.0-3" from PciRoot(0x0)/Pci(0x1,0x0)/USB(0x2,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU USB HARDDRIVE 1-0000:00:01.0-3" from PciRoot(0x0)/Pci(0x1,0x0)/USB(0x2,0x0)
/run/entry.sh: line 40:   191 Killed                  wsdd -i "$interface" -p -n "$hostname"
❯ ERROR: Forcefully terminating Windows, reason: 0...
❯ Shutdown completed!
❯ Starting Windows for Docker v4.20...
❯ For support visit https://github.com/dockur/windows-arm
❯ CPU: 0 | RAM: 7/8 GB | DISK: 1427 GB (/0x6a656a63) | KERNEL: 6.10.14-linuxkit...

❯ Booting Windows using QEMU v9.2.1...
UEFI firmware (version 2024.11-5 built at 00:55:52 on Jan 28 2025)
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU USB HARDDRIVE 1-0000:00:01.0-3" from PciRoot(0x0)/Pci(0x1,0x0)/USB(0x2,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU USB HARDDRIVE 1-0000:00:01.0-3" from PciRoot(0x0)/Pci(0x1,0x0)/USB(0x2,0x0)
/run/entry.sh: line 40:   191 Killed                  wsdd -i "$interface" -p -n "$hostname"
