### ISSUE TITLE
Windows 10 Container Loses Network Connectivity on Fedora 42 (Kernel 6.14.0)

### ISSUE THREAD

**Issue by diegodario88** [dockur/windows#1120]
### Operating system

Fedora 42

### Description

After updating to **Fedora 42** with **Kernel 6.14.0**, my Windows 10 container (using Docker/Podman) boots successfully but has **no network connectivity**. The host machine’s network works perfectly, and no errors appear in the container’s boot logs.

### Docker compose

```yml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - /mnt/kingston/windows-docker-volume:/storage
    extra_hosts:
      - "suindara.dev:172.17.0.1"
    environment:
      VERSION: "win10"
      RAM_SIZE: "16GB"
      CPU_CORES: 6
      DISK_SIZE: "100GB"
    security_opt:
      - seccomp=unconfined
    privileged: true

```

### Docker log

[+] Running 2/2
 ✔ Network windows-docker_default  Created                                                                          0.1s
 ✔ Container windows               Created                                                                          0.0s
WARN[0000] could not start menu, an error occurred while starting: Error while reading terminfo data:termbox: unsupported terminal
Attaching to windows
windows  | ❯ Starting Windows for Docker v2.07...
windows  | ❯ For support visit https://github.com/dockur/windows
windows  |
windows  | ❯ Booting Windows using QEMU emulator version 8.2.1 ...
windows  |
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,6E1F473B-3BD8-4939-9D06-BE12C60685B8,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
windows  | BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,6E1F473B-3BD8-4939-9D06-BE12C60685B8,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi

### Screenshots (optional)

![Image](https://github.com/user-attachments/assets/454224f6-ea0c-4a3e-a957-48b05c89dd4a)
