### ISSUE TITLE
Tiny11 fails to boot right after install

### ISSUE THREAD

**Issue by liontiger23** [dockur/windows#1177]
### Operating system

Solus

### Description

After installing tiny11, it fails to boot into windows.

### Docker compose

I am using basically default `compose.aml` from [winapps](https://github.com/winapps-org/winapps/blob/main/compose.yaml).

The only change is I downloaded tiny11 iso manually using link from dockur/windows [sources](https://github.com/dockur/windows/blob/81e9fff270a9304750ce42d4b90755304d57dd16/src/define.sh#L1046).

```
# For documentation, FAQ, additional configuration options and technical help, visit: https://github.com/dockur/windows

name: "winapps" # Docker Compose Project Name.
volumes:
  # Create Volume 'data'.
  # Located @ '/var/lib/docker/volumes/winapps_data/_data' (Docker).
  # Located @ '/var/lib/containers/storage/volumes/winapps_data/_data' or '~/.local/share/containers/storage/volumes/winapps_data/_data' (Podman).
  data:
services:
  windows:
    image: ghcr.io/dockur/windows:latest
    container_name: WinApps # Created Docker VM Name.
    environment:
      # Version of Windows to configure. For valid options, visit:
      # https://github.com/dockur/windows?tab=readme-ov-file#how-do-i-select-the-windows-version
      # https://github.com/dockur/windows?tab=readme-ov-file#how-do-i-install-a-custom-image
      VERSION: "tiny11"
      RAM_SIZE: "4G" # RAM allocated to the Windows VM.
      CPU_CORES: "4" # CPU cores allocated to the Windows VM.
      DISK_SIZE: "64G" # Size of the primary hard disk.
      #DISK2_SIZE: "32G" # Uncomment to add an additional hard disk to the Windows VM. Ensure it is mounted as a volume below.
      USERNAME: "MyWindowsUser" # Edit here to set a custom Windows username. The default is 'MyWindowsUser'.
      PASSWORD: "MyWindowsPassword" # Edit here to set a password for the Windows user. The default is 'MyWindowsPassword'.
      HOME: "${HOME}" # Set path to Linux user home folder.
    privileged: true # Grant the Windows VM extended privileges.
    ports:
      - 8006:8006 # Map '8006' on Linux host to '8006' on Windows VM --> For VNC Web Interface @ http://127.0.0.1:8006.
      - 3389:3389/tcp # Map '3389' on Linux host to '3389' on Windows VM --> For Remote Desktop Protocol (RDP).
      - 3389:3389/udp # Map '3389' on Linux host to '3389' on Windows VM --> For Remote Desktop Protocol (RDP).
    stop_grace_period: 120s # Wait 120 seconds before sending SIGTERM when attempting to shut down the Windows VM.
    restart: on-failure # Restart the Windows VM if the exit code indicates an error.
    volumes:
      - data:/storage # Mount volume 'data' to use as Windows 'C:' drive.
      - ${HOME}:/shared # Mount Linux user home directory @ '\\host.lan\Data'.
      #- /path/to/second/hard/disk:/storage2 # Uncomment to mount the second hard disk within the Windows VM. Ensure 'DISK2_SIZE' is specified above.
      #- ./oem:/oem # Enables automatic post-install execution of 'oem/install.bat', applying Windows registry modifications contained within 'oem/RDPApps.reg'.
      - /data/windows/tiny11_2311_x64.iso:/custom.iso # Uncomment to use a custom Windows ISO. If specified, 'VERSION' (e.g. 'tiny11') will be ignored.
    devices:
      - /dev/kvm # Enable KVM.
      #- /dev/sdX:/disk1 # Uncomment to mount a disk directly within the Windows VM (Note: 'disk1' will be mounted as the main drive. THIS DISK WILL BE FORMATTED BY DOCKER).
      #- /dev/sdY:/disk2 # Uncomment to mount a disk directly within the Windows VM (Note: 'disk2' and higher will be mounted as secondary drives. THIS DISK WILL NOT BE FORMATTED).
```

### Docker log

```
WinApps  | ❯ Starting Windows for Docker v4.28...
WinApps  | ❯ For support visit https://github.com/dockur/windows
WinApps  | ❯ CPU: Intel Core i5 6200U | RAM: 14/16 GB | DISK: 427 GB (ext4) | KERNEL: 6.12.19-315.current...
WinApps  | 
WinApps  | ❯ Extracting local ISO image...
WinApps  | ❯ Adding drivers to image...
WinApps  | ❯ Adding win11x64.xml for automatic installation...
WinApps  | ❯ Building Windows 11 image...
WinApps  | ❯ Creating a 64 GB growable disk image in raw format...
WinApps  | ❯ Booting Windows using QEMU v9.2.2...
WinApps  | BdsDxe: skipped Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
WinApps  | BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
WinApps  | BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
WinApps  | !!!! X64 Exception Type - 0E(#PF - Page-Fault)  CPU Apic ID - 00000000 !!!!
WinApps  | ExceptionData - 0000000000000003  I:0 R:0 U:0 W:1 P:1 PK:0 SS:0 SGX:0
WinApps  | RIP  - 00000000006AD5D3, CS  - 0000000000000038, RFLAGS - 0000000000010202
WinApps  | RAX  - 00000000007185B0, RCX - 00000000007185C0, RDX - 0000000000000002
WinApps  | RBX  - 00000000007141C8, RSP - 0000000000136DF8, RBP - 0000000000136F50
WinApps  | RSI  - 0000000000000000, RDI - 00000000007185B0
WinApps  | R8   - 0000000000000008, R9  - 0000000000000315, R10 - 0000000000000000
WinApps  | R11  - 0000000000724B0A, R12 - 0000000000000000, R13 - 000000000019E4A0
WinApps  | R14  - 000000000019F010, R15 - 0000000000113000
WinApps  | DS   - 0000000000000030, ES  - 0000000000000030, FS  - 0000000000000030
WinApps  | GS   - 0000000000000030, SS  - 0000000000000030
WinApps  | CR0  - 0000000080010033, CR2 - 00000000007185B0, CR3 - 000000007FC01000
WinApps  | CR4  - 0000000000040668, CR8 - 0000000000000000
WinApps  | DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
WinApps  | DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
WinApps  | GDTR - 000000007F9DC000 0000000000000047, LDTR - 0000000000000000
WinApps  | IDTR - 000000007F0F0018 0000000000000FFF,   TR - 0000000000000000
WinApps  | FXSAVE_STATE - 0000000000136A50
WinApps  | !!!! Find image based on IP(0x6AD5D3) bootmgr.pdb (ImageBase=000000000054A000, EntryPoint=000000000056D514) !!!!
WinApps  | ❯ Windows started succesfully, visit http://127.0.0.1:8006/ to view the screen...

```

### Screenshots (optional)

![Image](https://github.com/user-attachments/assets/cc3687bc-822a-498f-91cc-9c325f55dfa7)
