### ISSUE TITLE
[Question]: How can I run dotnet test inside the Docker Windows Container without using the web browser?

### ISSUE THREAD

**Issue by TesterEric** [dockur/windows#1179]
### Is your question not already answered in the FAQ?

- [x] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [x] I am sure my question is not about a technical issue.

### Question

How can I run a .NET test inside the Windows environment without using the web browser? 

I want to use a Dockurr\windows image, because my tests have a dependency with Windows dll's and can therefore not run in a Linux environment.  I was able to install the .NET SDK via the dotnet install scripting (https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) and the _install.bat_ file suggested in the "How do I run a script after installation" section of https://hub.docker.com/r/dockurr/windows.

I tried _docker exec windows dotnet test <dll>_ but it fails complaining "OCI runtime exec failed: exec failed: unable to start container process: exec: "dotnet": executable file not found in $PATH: unknown". It seems it wants to execute the tests in the Linux environment instead of Windows. Running the tests must be part of an automated build process, so manually starting the tests from the web browser (localhost:8006) is no option.

Hopefully someone can help so that I can continue?

**compose.yml**
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./win11x64.iso:/custom.iso
      - ./windows:/storage
      - ./install:/oem
    
    restart: always
```
    stop_grace_period: 2m

**install.bat** (install .NET SDK and set path)
```
cd c:\oem

echo Install .NET SDK in c:\dotnet
Powershell.exe -ExecutionPolicy Unrestricted -File ./dotnet-install.ps1 -InstallDir c:\dotnet

echo Add c:\dotnet to Path environment variable (persistent)
Powershell.exe [Environment]::SetEnvironmentVariable('Path', $env:Path + ';c:\dotnet', 'Machine')
```

**Comment by TesterEric** [comment]
@kroeze, it seems there is no installer available for freerdp2 (only sources). Does anyone have experience on how to install and use freerdp on a Windows host system to connect to dockurr\windows container to be able to execute an executable running on Windows (in the container)?

**Comment by TesterEric** [comment]
@kroese , thanks again for the answer. The Invoke-Command (you are referring to) needs a computer name in order to make the connection. Since Windows is running inside the Docker container, which computer name should I use?

**Comment by TesterEric** [comment]
I am still not able to make a remote connection to the Windows environment running in the Docker container.  It is not clear which computer name or ip address I have to use to make the connection.

**Comment by TesterEric** [comment]
@kroese , thanks, it is working now with the PS Invoke-Command and using the WinRM port.

**Comment by mhagnumdw** [comment]
@TesterEric, could you share the steps you took to configure WinRM?

**Comment by TesterEric** [comment]
@mhagnumdw , winrm does not work on Linux meaning that we could not use winrm port 5985 to connect with Windows. We managed to get ssh working, but by default the ssh port is not exposed by the Docker image. You have to configure it as USER mode networking and add port 22. With port forwarding you access ssh port 22 and execute commands inside the Windows environment on Docker.
```

      containers:
      - name: my-container
        image: dockurr/windows:5.06
        
        env:
        - name: DISK_SIZE
          value: "64G"
        - name: USER_PORTS
          value: "22"
        - name: NETWORK
          value: "user"
```
