### ISSUE TITLE
[Feature]: Preinstalled windows

### ISSUE THREAD

**Issue by nguyenducminh11102012** [dockur/windows#1187]
### Is your proposal related to a problem?

I'm always frustrated when I have to wait the windows to be installed

### Describe the solution you'd like.

Hi!
I have used this service a lot and it is great. However, I have to wait a long time for windows to be installed

### Describe alternatives you've considered.

I have used this service a lot and feel great. However, it would be great if you could pre-install some windows and package it into a disk.raw file for example, so when installing, I won't have to wait for the installation time but it will go straight into the system.

**Comment by ItzLevvie** [comment]
You can do it by yourself - it is something like https://github.com/ItzLevvie/dind#:~:text=Hyper%2DV%20will%20store%20your%20VHDX%20file

1) Install Windows on Hyper-V with the VirtIO drivers installed.
2) Send the VHDX to Codespaces
3) Split the VHDX into 4 files (1 GB each)
4) Upload VHDX to GitHub Releases
5) Edit your script to download the VHDX from GitHub Releases, extract all 4 files, and then convert from data.vhdx to data.img using qemu-img - https://github.com/ItzLevvie/dind/blob/5e160bf4d62bc474e5eb66029aeaf0de278258dc/.devcontainer/postCreateCommand.sh#L25-L34

**Comment by eberteogam** [comment]
> [@nguyenducminh11102012](https://github.com/nguyenducminh11102012) Normally you have to only install it once? The second time you run the container it should just continue where you left off, or something is wrong (hard to tell now without compose file / log files).
> 
> If there is another reason why you need to wait till its installed (for example, if you use the container for testing and you want to start with a clean slate each time) you can just take a copy of the `/storage` folder after installation, and always use that copy when you create a new container.

Actually I'm looking to do so. I noticed deleting the container and composing a new one doesn't give you a fresh start. I also tried to comment out the volume line but it did not work. This is my .yml

```
services:
  windows:
    image: dockurr/windows
    container_name: windows11CSM
    environment:
      VERSION: "11"
      RAM_SIZE: "12G"
      CPU_CORES: "6"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
#    volumes:
#      - ./windows:/storage
    restart: no
    stop_grace_period: 2m
```
and this is what I have in windows folder:

```
>/windows$ ls
data.img  windows.base  windows.boot  windows.mac  windows.rom  windows.vars  windows.ver
```

I also don't like the idea to download the Windows iso everytime I'd like to do a fresh start, it's time-consuming. Any advice?
