### ISSUE TITLE
Enabling Hyper-V for nested virtualization causes problems

### ISSUE THREAD

**Issue by GThumeAdigo** [dockur/windows#1191]
### Operating system

openSUSE Tumbleweed

### Description

Dear Maintainer and Community , I need some help to get Hyper-V working.
I am required to work with Windows Containers with the isolation mode Hyper-V for my Job.

For Example something like:

```
docker run -it --isolation=hyperv mcr.microsoft.com/windows/servercore:ltsc2019 cmd
```

Right now, whenever I enable Hyper-V with the ps command below, i get the blue "automatic repair" screen when restarting. 

```ps
Install-WindowsFeature -Name Hyper-V  -IncludeManagementTools 
```

When I try enabling the feature within the Windows Server Manager, i get the Error that my processor isn't supporting VMX.

I checked my bios, and ran kvm-ok, but everything seemed fine.
I went through some closed issues and found #265 which gave me some hints, but didn't fix my problem.
Also, I've tried several different Windows versions, and added different values (like HV = "Y" or VMX = "Y") to the environment section of the docker-compose.yml but nothing worked so far.

### Docker compose

```yml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    networks:
      BcContainerNetwork:
        ipv4_address: 172.20.0.100
    environment:
      VERSION: "25"
      # EDITION: "core"
      REGION: "de-DE"
      KEYBOARD: "de-DE"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      DISK_SIZE: "64G"
      USERNAME: "admin"
      PASSWORD: "admin"
      # HV: "Y"
      VMX: "Y"
      ARGUMENTS: "-cpu host,-vmx"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443
      - 80:80
      - 8080:8080
      - 7048:7048
      - 7047:7047
      - 7049:7049
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./storage:/storage
      - ./data-exchange:/data
      - ./startup-scripts:/oem
    privileged: true
    restart: always
    stop_grace_period: 2m

networks:
  BcContainerNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
```

### Docker log

❯ Extracting Windows Server 2025 image...
❯ Adding drivers to image...
❯ Adding OEM folder to image...
❯ Adding win2025-eval.xml for automatic installation...
❯ Building Windows Server 2025 image...
❯ Creating a 64 GB growable disk image in raw format...
❯ Booting Windows using QEMU v9.2.2...
BdsDxe: skipped Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
❯ Windows started succesfully, visit http://127.0.0.1:8006/ to view the screen...
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,E08B74BE-461B-4322-AB87-6476558DE278,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi

### Screenshots (optional)

![Image](https://github.com/user-attachments/assets/ac018504-d999-4c3f-beaa-ad5d18ca625f)

![Image](https://github.com/user-attachments/assets/0c2d27d3-0b2f-4096-a042-8cc8996ff4d9)

**Comment by nwrkbiz** [comment]
You will have the same error too within virt-manager. The problem is the CPU-Type. In virt-manager i did choose one that was matching my real hardware. This was my setting:

```
  <cpu mode="custom" match="exact" check="partial">
    <model fallback="allow">Broadwell-noTSX-IBRS</model>
    <topology sockets="1" dies="1" cores="6" threads="1"/>
    <feature policy="disable" name="hypervisor"/>
    <feature policy="require" name="vmx"/>
    <feature policy="disable" name="mpx"/>
  </cpu>
```

**Comment by nwrkbiz** [comment]
@GThumeAdigo This environment variable worked for me with docur:

ARGUMENTS="-cpu Broadwell-noTSX-IBRS,hypervisor=off,vmx=on,mpx=off,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff"

**Comment by GThumeAdigo** [comment]
Awsome @nwrkbiz thanks for your help, it finally works now!!

Here is my compose file, if anybody is interested:

 ``` yml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    networks:
      BcContainerNetwork:
        ipv4_address: 172.20.0.100
    environment:
      VERSION: "25"
      # EDITION: "core"
      REGION: "de-DE"
      KEYBOARD: "de-DE"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      DISK_SIZE: "64G"
      USERNAME: "admin"
      PASSWORD: "admin"
      VMX: "Y"
      ARGUMENTS: "-cpu Broadwell-noTSX-IBRS,hypervisor=off,vmx=on,mpx=off,hv-time=on,hv-relaxed=on,hv-vapic=on,hv-spinlocks=0x1fff"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443
      - 80:80
      - 8080:8080
      - 7048:7048
      - 7047:7047
      - 7049:7049
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./storage:/storage
      - ./data-exchange:/data
      - ./startup-scripts:/oem
    privileged: true
    restart: unless-stopped
    stop_grace_period: 2m

networks:
  BcContainerNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

```


I also have a startup script that enables Hyper-V and installs Docker for running Windows containers:

```bat
echo Enabling Hyper-V without restarting directly
powershell -Command "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All -NoRestart"
echo Successfully enabled Hyper-V

echo Installing Docker...
powershell -Command "Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1' -o install-docker-ce.ps1"
powershell -Command ".\install-docker-ce.ps1"
```
