### ISSUE TITLE
sharing wireguard vpn in docker compose stopped working

### ISSUE THREAD

**Issue by acornnugget** [dockur/windows#1196]
### Operating system

Ubuntu 24.04.2 LTS

### Description

I have docker-compose.yml as shown below. in ./wg i have wg0.conf for wireguard.

It used to work (last i know for sure was end of december 2024) but it does not any more for some reason.

From either of the containers (docker exec -it windows | wireguard bash ) i can connect to outside network and wget ipinfo.io shows that VPN is up and working. 

From inside windows, when trying to ping outside, the host name is resolved, but that's all. It used to work flawlessly - i was able to browse internet via VPN.

for what its worth, network configuration inside windows container:

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host proto kernel_lo 
       valid_lft forever preferred_lft forever
3: dockerbridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b2:9c:2b:0d:c0:79 brd ff:ff:ff:ff:ff:ff
    inet 20.20.20.1/24 brd 20.20.20.255 scope global dockerbridge
       valid_lft forever preferred_lft forever
    inet6 fe80::281a:80ff:fe42:6e9f/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
4: qemu: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc fq_codel master dockerbridge state UP group default qlen 1000
    link/ether b2:9c:2b:0d:c0:79 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::b09c:2bff:fe0d:c079/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
5: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.2.0.2/32 scope global wg0
       valid_lft forever preferred_lft forever
53: eth0@if54: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.2/16 brd 172.19.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

and inside wireguard:

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host proto kernel_lo 
       valid_lft forever preferred_lft forever
3: dockerbridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b2:9c:2b:0d:c0:79 brd ff:ff:ff:ff:ff:ff
    inet 20.20.20.1/24 brd 20.20.20.255 scope global dockerbridge
       valid_lft forever preferred_lft forever
    inet6 fe80::281a:80ff:fe42:6e9f/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
4: qemu: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc fq_codel master dockerbridge state UP group default qlen 1000
    link/ether b2:9c:2b:0d:c0:79 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::b09c:2bff:fe0d:c079/64 scope link proto kernel_ll 
       valid_lft forever preferred_lft forever
5: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none 
    inet 10.2.0.2/32 scope global wg0
       valid_lft forever preferred_lft forever
53: eth0@if54: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:13:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.19.0.2/16 brd 172.19.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

### Docker compose

```yml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "7e"
      USERNAME: "docker"
      PASSWORD: "docker"
    volumes:
      - ./win:/data
      - ./winsys:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    network_mode: service:wireguard
    depends_on:
      - wireguard

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    networks:
      - net01
    volumes:
      - "./wg:/config"
      - "/lib/modules:/lib/modules:ro"
    environment:
      - PUID=1000
      - PGID=1000
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - 0.0.0.0:3389:3389/tcp

networks:
  net01:
    driver: bridge
```

### Docker log

❯ Starting Windows for Docker v4.05...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Core i7 9850H | RAM: 9/31 GB | DISK: 197 GB (ext4) | KERNEL: 6.11.0-21...

ESC[1;34m❯ ESC[1;36mHost: 6f790be0601e  IP: 172.19.0.2  Gateway: 172.19.0.1  Interface: eth0  MAC: 02:03:1E:DF:81:FDESC[0m
nameserver 127.0.0.11

Arguments:

-nodefaults
-cpu host,kvm=on,l3-cache=on,+hypervisor,migratable=no,-vmx
-smp 2,sockets=1,dies=1,cores=2,threads=1
-m 4G
-machine type=q35,smm=on,graphics=off,vmport=off,dump-guest-core=off,hpet=off,accel=kvm
-enable-kvm
-global kvm-pit.lost_tick_policy=discard
-display vnc=:0,websocket=5700
-vga virtio
-monitor telnet:localhost:7100,server,nowait,nodelay
-daemonize
-D /run/shm/qemu.log
-pidfile /run/shm/qemu.pid
-name windows,process=windows,debug-threads=on
-serial pty
-device usb-ehci,id=ehci
-device usb-tablet
-netdev tap,id=hostnet0,ifname=qemu,script=no,downscript=no
-device virtio-net-pci,romfile=,netdev=hostnet0,mac=02:03:1E:DF:81:FD,id=net0
-drive file=/storage/data.img,id=data3,format=raw,cache=none,aio=native,discard=on,detect-zeroes=on,if=none
-device virtio-scsi-pci,id=data3b,bus=pcie.0,addr=0xa,iothread=io2
-device scsi-hd,drive=data3,bus=data3b.0,channel=0,scsi-id=0,lun=0,rotation_rate=1,bootindex=3
-object iothread,id=io2
-rtc base=localtime
-global ICH9-LPC.disable_s3=1
-global ICH9-LPC.disable_s4=1
-object rng-random,id=objrng0,filename=/dev/urandom
-device virtio-rng-pci,rng=objrng0,id=rng0,bus=pcie.0,addr=0x1c 
ESC[1;34m❯ ESC[1;36mBooting Windows (legacy) using QEMU v9.1.1...ESC[0m
ESCcESC[?7lESC[2JESC[0mSeaBIOS (version 1.16.3-debian-1.16.3-2)
Booting from Hard Disk...
ESC[01;01HESC[1;34m❯ ESC[1;36mWindows started succesfully, visit http://localhost:8006/ to view the screen...ESC[0m

### Screenshots (optional)

![Image](https://github.com/user-attachments/assets/827decf0-0a96-4338-bde6-af87a6056b54)
