### ISSUE TITLE
Unable to use personal ISO normally

### ISSUE THREAD

**Issue by quxinyua** [dockur/windows#1222]
### Operating system

ubuntu 22.04

### Description

I have encapsulated an ISO for windows_10upro with 10 software components. The encapsulated image uses' administrator '. If I do not specify the username' USERNAME 'in the configuration, a Docker user will be created. Even if I specify the username' administrator ', the encapsulated software will be lost after successful startup. But if I manually install the entire process, I won't lose it. Why is that?

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows:latest
    container_name: windows
    environment:
      VERSION: "boot.iso"
      CPU_CORES: "2"
      RAM_SIZE: "4G"
      USERNAME: "Administrator"
        #PASSWORD: "admin123"
      LANGUAGE: "CN"
        #MANUAL: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./windows_10_22h2.iso:/boot.iso
    restart: always
    stop_grace_period: 2m
```

### Docker log

```shell
❯ Starting Windows for Docker v4.33...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Core Broadwell IBRS  | RAM: 6/8 GB | DISK: 57 GB (ext4) | KERNEL: 6.11.0-21...

❯ Extracting local ISO image...
❯ Detecting version from ISO image...
❯ Detected: Windows 10 Pro (Chinese)
❯ Adding drivers to image...
❯ Adding win10x64.xml for automatic installation...
❯ Building Windows 10 image...
❯ Creating a 64 GB growable disk image in raw format...
❯ Nested KVM virtualization detected..
❯ Booting Windows securely using QEMU v9.2.92...
BdsDxe: skipped Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
❯ Windows started succesfully, visit http://127.0.0.1:8006/ to view the screen...
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,7A4C4B59-E41B-45FC-A1B4-34A1C2EAD148,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,7A4C4B59-E41B-45FC-A1B4-34A1C2EAD148,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
```
