### ISSUE TITLE
tap windows setup  xxxx  requires administrator privilege

### ISSUE THREAD

**Issue by AlvinCage** [dockur/windows#1223]
### Operating system

Ubuntu 24.4

### Description

**tap windows setup  xxxx  requires administrator privilege？**
When I install exe on the Windows 10 system, it prompts that administrator privileges are required; But who can tell me what the password for this Docker user is, otherwise I won't be able to install most exe software as an administrator

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "128G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./data:/storage
    restart: always
    stop_grace_period: 2m
```

### Docker log

```shell
❯ Booting Windows using QEMU v9.2.92...
BdsDxe: skipped Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
❯ Windows started succesfully, visit http://127.0.0.1:8006/ to view the screen...
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,88B2C1E8-BFD3-4816-8316-956350668FFE,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,88B2C1E8-BFD3-4816-8316-956350668FFE,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,88B2C1E8-BFD3-4816-8316-956350668FFE,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,88B2C1E8-BFD3-4816-8316-956350668FFE,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,88B2C1E8-BFD3-4816-8316-956350668FFE,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,88B2C1E8-BFD3-4816-8316-956350668FFE,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
```

### Screenshots (optional)

![Image](https://github.com/user-attachments/as

![Image](https://github.com/user-attachments/assets/cde0a115-46f1-4d37-804a-0fe21b7c4a01)

sets/77e4326c-a8e8-443f-b892-782c8c9c5377)
