### ISSUE TITLE
[Question]: Update Kubernetes documentation on how to add user ports

### ISSUE THREAD

**Issue by TesterEric** [dockur/windows#1236]
### Is your question not already answered in the FAQ?

- [x] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [x] I am sure my question is not about a technical issue.

### Question

If I understand correctly only ports 8006. 3389 and 5900 are supported by the image. For my project I need to connect to winrm port 5985, which seems not to be supported.

I was able to do the port forwarding and establish a connection to 5985 by adding environment variables specifying port 5985 to the containers section of the deployment pod:

```
containers:
- name: container
   image: dockurr/windows
   env:
   - name: USER_PORTS
      value: "5985"
   - name: NETWORK
      value: "user"
```

I had to dive into the run/network.sh script to figure out how it works. 

With this question I want to request to update the documentation of dockurr\windows with a section on how to add user ports to the configuration so that a deep dive into the Linux environment is not needed in the future.
