### ISSUE TITLE
[Bug]: UDP port listening broken on 4.40.0 and newer versions

### ISSUE THREAD

**Issue by dvv47** [dockur/windows#1245]
### Operating system

Ubuntu 22.04 and Ubuntu 24.04

### Description

udp port is binded to cotainer - "54603:54603/udp"

and docker inspect shows it correctly
```
"PortBindings": {
			"54603/udp": [
				{
					"HostIp": "",
					"HostPort": "54603"
				}
			],
		},
```

But udp traffic work only for first start of udp server inside this container

After restarting of udp server inside container, udp port is not forwarding to container anymore
Its possible to fix only after restarting entire container

Last version where it works good is 4.39.0

4.40, 4.41.x all have this issue

### Docker compose

```yaml
# This is a replace for run_docker.sh
services:
  rwc_dev:
    extends:
      file: dev.yaml
      service: dev

    container_name: dev

    volumes:
      # tools
      - type: bind
        source: $HOME/.gitconfig
        target: /home/oper/.gitconfig

      # Video devices
      - /var/run/dbus:/var/run/dbus
      - /run/shm:/run/shm
      - /dev/shm:/dev/shm
      #   - USB camera
      - /run/ueyed:/run/ueyed

      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "7001:7001"
      - "7002:7002"
      - "54603:54603/udp"
      - "47000-47005:47000-47005"

    networks:
      front:

    privileged: true
    
    command: ["/entrypoint.sh"]

networks:
  front:
    external: false
    name: front
```

### Docker log

```shell
...
```
