### ISSUE TITLE
[Bug]: Windows Server 2008 R2 not accepting "admin" as password for "Docker" user.

### ISSUE THREAD

**Issue by hnine999** [dockur/windows#1249]
### Operating system

Ubuntu22.04

### Description

Expected behavior:  Connection with RDP client using Username=Docker, Password=admin is successful.

Actual behavior:  Connect with RDP client using Username=Docker, Password=admin fails with authentication error.

Steps to reproduce:  Use RDP client to try to connect to localhost:3389, User=Docker, Password=admin

It will not connect.

FIX:
Using the `localhost:8006` web interface, disable **Password must meet complexity requirements**:

1. Start → Run → secpol.msc
2. Double-click **Password must meet complexity requirements**.
3. Set it to **Disabled**

Is there a way do this during installation?

To set Docker password to "admin"
In a command prompt:
1. enter the command "net user %username% *"
2. Enter "admin" at the prompts

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2008"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
```

### Docker log

```shell
SeaBIOS (version 1.16.3-debian-1.16.3-2)
Booting from Hard Disk...
❯ Windows started succesfully, visit http://127.0.0.1:8006/ to view the screen...
```

**Comment by softplaceio** [comment]
Set PATH: ISO

```
version: '3.8'

networks:
  mydesktop:
    name: mydesktop
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  # CONTAINER: WINDOWS SERVER 2014
  winserver:
    image: dockurr/windows
    container_name: "winserver"
    hostname: Windows-Host
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 120s
    restart: on-failure
    environment:
      - VERSION="2016"
      - RAM_SIZE=4G
      - CPU_CORES=4
      - DISK_SIZE=60G
      - USERNAME="Windows"
      - PASSWORD=""
    volumes:
      - /home/linux/ISO/WS2016R2x64.iso:/boot.iso
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    networks:
      mydesktop:
        ipv4_address: 172.20.0.10

  # CONTAINER: WINDOWS 11 PRO
  win11pro:
    image: dockurr/windows
    container_name: "win11pro"
    hostname: Windows-Host
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 120s
    restart: on-failure
    environment:
      - VERSION="win11"
      - RAM_SIZE=4G
      - CPU_CORES=4
      - DISK_SIZE=60G
      - USERNAME="Windows"
      - PASSWORD=""
    volumes:
      - /home/linux/ISO/W11ProX64_22H2_Lite_WithTPM.iso:/boot.iso
    ports:
      - "8007:8006"
      - "3390:3389/tcp"
      - "3390:3389/udp"
    networks:
      mydesktop:
        ipv4_address: 172.20.0.20


```
