### ISSUE TITLE
Can not address hostnames of other services running the same compose file as dockurr/windows

### ISSUE THREAD

**Issue by duysqubix** [dockur/windows#1252]
### Operating system

Windows 11 Pro

### Description

When spinning up another service within the same compose file, by default the network is bridged. In the following compose file and can land in the ubuntu container hosting the VM and do a `ping postgres-repo` and it works. This feature doesn't work when doing a `PING postgres-repo` in the VM itself. 

The only way I can connect to another service is by using the assigned docker IP , which in my case doing a `ping 172.xx.xx.xx` works and it gets packets back. 

Any idea on how to make the DNS hostnames available in the VM?

### Docker compose

```yaml
name: red10-snowflake-env
services:
  red10-3D-snowflake:
    image: dockurr/windows
    container_name: red10-3d-snowflake
    environment:
      VERSION: "11"
      WINDOWS_KEY: # Your Windows 11 license key
      DISK_SIZE: "50G"
      RAM_SIZE: "8G"
      CPU_CORES: "16"
      USERNAME: "wsuser"
      PASSWORD: "wsuser"
      REGION": "en-US"
      KEYBOARD: "en-US"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006" # Web-based viewer port
      - "3390:3389" # Remote Desktop Protocol (RDP) port
    volumes:
      - C:\WSDocker\data\red10-3d-snowflake\storage:/storage
      - C:\WSDocker\resources:/data
      - C:\WSDocker\resources\win11x64.iso:/boot.iso

  postgres-repo:
    image: postgres:16.9-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "repo"
    ports:
      - "5000:5432"
    volumes:
      - C:\WSDocker\data\red10-3d-snowflake\postgres-repo:/var/lib/postgresql/data

    depends_on:
      - red10-3D-snowflake
```

### Docker log

```shell
Starting Windows for Docker v4.35...

❯ For support visit https://github.com/dockur/windows⁠

❯ CPU: Intel Core i9 14900KF | RAM: 62/63 GB | DISK: 850 GB (v9fs) | KERNEL: 5.15.167.4-microsoft-standard-WSL2...


❯ Detected that your custom .iso file was changed, but ignoring this because Windows is already installed.

❯ Please start with an empty /storage folder, if you want to install a different version of Windows.

❯ Booting Windows using QEMU v10.0.0...

BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,05FB0ED8-5A28-425A-AA7C-311C554E0D56,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi

BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,05FB0ED8-5A28-425A-AA7C-311C554E0D56,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi

❯ Windows started succesfully, visit http://127.0.0.1:8006/⁠ to view the screen...
```

**Comment by duysqubix** [comment]
Bumping! I've been tearing my hair out with networking concepts to try to get this to work. 

I've been messing around with utilizing a [dns proxy server](https://github.com/mageddo/dns-proxy-server) to try to route the internal VM to the proxy just to get name resolution solved, but that's not working either. 

Any ideas?

**Comment by kroese** [comment]
Yeah that is really complicated, because the container is running in the bridge network, but the Windows installation is running behind a tunnel, which prevents the communication to other containers in the same bridge network. 

The easiest solution is to use macvlan/dhcp mode as described in the README, as that removes the tunneling and puts the Windows installation directly on the network. But that doesn't work with Docker Desktop for Windows, only on Linux systems.

So I have no quick solution for you. If you own a domain name, you could make subdomain DNS entries with the local IP's of the other containers, so you can ping `machine34.example.com` instead of `machine34`. But that is no real alternative, because you would have to manually manage those entries. Im sorry, but I dont have a better solution.

**Comment by duysqubix** [comment]
> Yeah that is really complicated, because the container is running in the bridge network, but the Windows installation is running behind a tunnel, which prevents the communication to other containers in the same bridge network. 
> 
> The easiest solution is to use macvlan/dhcp mode as described in the README, as that removes the tunneling and puts the Windows installation directly on the network. But that doesn't work with Docker Desktop for Windows, only on Linux systems.
> 
> So I have no quick solution for you. If you own a domain name, you could make subdomain DNS entries with the local IP's of the other containers, so you can ping `machine34.example.com` instead of `machine34`. But that is no real alternative, because you would have to manually manage those entries. Im sorry, but I dont have a better solution.

This maybe a stupid question, but wouldn't this work if we made the vm in qemu share the hosts (docker container in this case) network with the vm itself?

So similar with docker how you'd do --network host.

**Comment by duysqubix** [comment]
@kroese 

Just to add-- within the VM you can directly input other containers ip addresses and it will ping fine. But the host name won't resolve.

**Comment by kroese** [comment]
@duysqubix Good news! I just discovered you can ping them by using `containername.networkname` and it will resolve the containers IP correctly. So for example `postgres-repo.mybridge` instead of just ` postgres-repo`.

**Comment by duysqubix** [comment]
@kroese that is great news! Is the default bridge name related to the containers bridge name, right?

**Comment by rchitulescu** [comment]
> [@duysqubix](https://github.com/duysqubix) Good news! I just discovered you can ping them by using `containername.networkname` and it will resolve the containers IP correctly. So for example `postgres-repo.mybridge` instead of just ` postgres-repo`.

Hi,

Sorry for jumping in on this topic, but how could one do it the other way around? 
How could one access the windows from postgres-repo service, how could one ping that windows from the postgres-repo service?

**Comment by kroese** [comment]
@rchitulescu The other way around is not really possible, because the VM is behind a NAT tunnel. The only way to remove this tunnel is to set `DHCP=Y` and the VM will be pingable by `postgres-repo`. But then it will also not be part of the bridge network, so it will not be able to ping `postgres-repo.mybridge` anymore. So it is one way or the other.

**Comment by duysqubix** [comment]
Technically solved based on my original submission. For future readers stumbling upon this. 

You can group other docker services in the same compose file (or share a docker network) with dockurr/windows. 

Within the VM itself, you can address other services, as pointed out by @kroese, with the following syntax `[container_name].[network_name]`

A simple example. 

```yaml
name: example

networks:
  default:
    name: my-network

services:
  vm:
    image: dockurr/windows
    ...

   db:
     image: postgres
     ...
```

Within the docker network, if you *shell-into* `db` you can reach the `vm` service by `ping vm`. 

Within the actual VM in the `vm` service you can also address the rest of the compose services within the command prompt window with:

`ping vm.my-network` 

No more setting static ip addresses to circumvent this issue!

Thanks @kroese for shedding some light on this!
