### ISSUE TITLE
Boot loop - How do I catch the logs?

### ISSUE THREAD

**Issue by profucius** [dockur/windows#1255]
### Operating system

Proxmox LXC

### Description

Last night, my Proxmox machine ran a scheduled backup. It stopped the Windows LXC container, took a snapshot, and brought it back online. However after this job, my Windows OS will not boot, it gets stuck in a boot loop. I also cannot seem to find the logs that would indicate the cause of the issue. Can someone please point me in the right direction to start diagnosis?

Below are the only logs I can capture from the console output. I'm running it as a stack in Portainer and I only see "ERROR: Forcefully terminating Windows, reason: 0" with no further debug info in the output.

One more thing to note, after a few loop cycles, the whole LXC seems to run at full CPU and be unresponsive until I force stop it.

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: unless-stopped
    privileged: true 
    environment:
      TZ: "America/New_York"
      MANUAL: "Y"
      RAM_SIZE: "8G"
      CPU_CORES: "8"
      DISK_SIZE: "20G" 
      DISK2_SIZE: "100G" 
      DHCP: "Y" 
    devices:
      - /dev/kvm 
      - /dev/net/tun 
      - /dev/vhost-net 
    volumes:
      - /home/rawos/:/storage 
      - /home/HDD2TB/windows-lxc:/storage2 
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      vlan:
        ipv4_address: 192.168.1.128 
networks:
  vlan:
    external: true
```

### Docker log

```shell
Below chunk loops infinitely:

❯ Starting Windows for Docker v4.35...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Core i9 9900K | RAM: 27/63 GB | DISK: 8 GB (ext4) | KERNEL: 6.8.12-10-pve...
❯ Booting Windows using QEMU v10.0.0...
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,A2BAA01D-2D04-4B38-A30B-F9B15322692B,0x800,0x32000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,A2BAA01D-2D04-4B38-A30B-F9B15322692B,0x800,0x32000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ ERROR: Forcefully terminating Windows, reason: 0...
❯ Shutdown completed!
```
