### ISSUE TITLE
Error `0x708` when connecting to Windows XP via RDP (`mstsc`)

### ISSUE THREAD

**Issue by TheJanzap** [dockur/windows#1256]
### Operating system

Windows 11 24H2

### Description

I've started up a Windows XP container with a basic configuration. I can access the web interface via `http://localhost:8006/`, but connecting to RDP via `mstsc` doesn't work.

- `localhost` and `127.0.0.1` result in "Your computer could not connect to another console session on the remote computer because you already have a console session in progress."
- `127.0.0.2` brings me to a login prompt, but the credentials specified in the README don't work (`Docker`, `admin`)
- Entering the IP returned from  `docker inspect -f "{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}" windows` does not connect to anything

Am I missing something?

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "xp"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006 # Web VNC
      - 3389:3389/tcp # RDP
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
```

### Docker log

```shell
❯ Starting Windows for Docker v4.35...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Core i7 1355U | RAM: 6/8 GB | DISK: 514 GB (v9fs) | KERNEL: 5.15.167.4-microsoft-standard-WSL2...
[1;34m❯ [1;36mBooting Windows (legacy) using QEMU v10.0.0...[0m
c[?7lSeaBIOS (version 1.16.3-debian-1.16.3-2)
Booting from Hard Disk...
c[?7l
[1;34m❯ [1;36mWindows started succesfully, visit http://127.0.0.1:8006/ to view the screen...[0m
```
