### ISSUE TITLE
Fail to up

### ISSUE THREAD

**Issue by skn41** [dockur/windows#1266]
### Operating system

Open Media Vault - Debian 11.21

### Description

![Image](https://github.com/user-attachments/assets/cea1ce56-b6ae-40ca-9ef4-479471772b98)

Has anyone experienced an error like this?

### Docker compose

```yaml
---
# Date: 2025-06-01
# https://github.com/dockur/windows
# see github page for many more options and windows versions 
services:
  windows:
    image: dockurr/windows
    container_name: windows
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/windows:/storage
    environment:
      VERSION: "11"
      #LANGUAGE: "French"
      #REGION: "en-US"
      #KEYBOARD: "en-US"
      #DISK_SIZE: "256G"
      #RAM_SIZE: "8G"
      #CPU_CORES: "4"
      #USERNAME: "bill"
      #PASSWORD: "gates"
      #DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```

### Docker log

```shell
No log file
```
