### ISSUE TITLE
Network interface 'eth0' does not exist inside the container

### ISSUE THREAD

**Issue by joyce7709** [dockur/windows#1267]
### Operating system

Ubuntu 20.04

### Description

I met an error "ERROR: Network interface 'eth0' does not exist inside the container!
❯ ERROR: Please add the following setting to your container: -e "VM_NET_DEV=NAME" to specify another interface name." when I using gVisor as my docker runtime. What should I do? Thank you for your help!

### Docker compose

```yaml
services:
  windows10:
    image: dockurr/windows
    container_name: windows10
    environment:
        USERNAME: "bill"
        PASSWORD: "gates"
        DISK_SIZE: "50G"
    devices:
        - /dev/kvm
    cap_add:
        - NET_ADMIN
    ports:
        - 7010:8006
        - 13310:3389/tcp
        - 13310:3389/udp
    stop_grace_period: 2m
    volumes:
      - ./win10/storage:/storage
      - ./win10/data:/data
      - ./win10_LTSC.ISO:/custom.iso
```

### Docker log

```shell
windows10  | ❯ Starting Windows for Docker v4.05...
windows10  | ❯ For support visit https://github.com/dockur/windows
windows10  | ❯ CPU: unknown | RAM: 7/8 GB | DISK: 36 GB (v9fs) | KERNEL: 4.4.0...
windows10  | 
windows10  | ❯ Extracting local ISO image...
windows10  | ❯ Detecting version from ISO image...
windows10  | ❯ Detected: Windows 10 LTSC (Chinese)
windows10  | ❯ Adding drivers to image...
windows10  | ❯ Adding win10x64-ltsc.xml for automatic installation...
windows10  | ❯ Building Windows 10 image...
windows10  | ❯ Creating a 50G growable disk image in raw format...
windows10  | ❯ ERROR: Network interface 'eth0' does not exist inside the container!
windows10  | ❯ ERROR: Please add the following setting to your container: -e "VM_NET_DEV=NAME" to specify another interface name.
```
