### ISSUE TITLE
The Windows system in the container has an independent IP address in the same network segment as the host

### ISSUE THREAD

**Issue by Eileentyt** [dockur/windows#1279]
### Operating system

Windows11

### Description

How to enable Windows 10 to access the internet normally and have an independent IP address in the same network segment as the host after starting the Windows 10 system in a container

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows
    container_name: win10_64
    environment:
      VERSION: "10"
      LANGUAGE: "Chinese"
      RAM_SIZE: "2G"
      CPU_CORES: "1"
    devices:
      - /dev/kvm
      - /dev/vhost-net
      - /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./share:/data
      - ./docker_test:/oem
    restart: always
    stop_grace_period: 2m
```

### Docker log

```shell
null
```
