### ISSUE TITLE
[Question]: Using a windows VM that was built using using dockur/windows in another dockur/windows container

### ISSUE THREAD

**Issue by hnine999** [dockur/windows#1280]
### Is your question not already answered in the FAQ?

- [x] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [x] I am sure my question is not about a technical issue.

### Question

A windows VM was built and provisioned using `dockur/windows`, specifically using the docker compose file below along with a custom `install.bat` script in /OEM.
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2022"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 2222:22
    volumes:
      - ./windows:/storage
      - ../Files:/data
      - ./OEM:/oem
    restart: always
    stop_grace_period: 2m

```

Once the windows VM was fully provisioned, it was shut down.

The resulting VM image was in `windows/data.img`, i.e. in the default `windows` directory in the file `data.img`.

The `data.img` file was converted from raw format into a compressed qcow2 file and stored elsewhere. 

Now, I would like to use the qcow2 file in another `dockur/windows` container, that is, not rebuild a windows VM from scratch (i.e. from an iso).

How is this done?

I tried recreating the windows directory and converting the qcow2 image into the raw `windows/data.img` file, but performing `docker compose up` started creating a new windows VM and overwrote the `data.img` file.

There are several other files in the `windows` directory that I did not recreate/restore:

```
windows.base
windows.mac
windows.mode
windows_secure.rom
windows_secure.tpm
windows_secure.vars
windows.ver
```

(intentionally left out `win2022-eval.iso`)

Are these needed in addition to the `data.img` file?  Can they be recreated so that the `data.img` file from the qcow2 image is used in the container?

Thanks.

**Comment by hnine999** [comment]
After examining the shell code used to implement the `dockurr/windows` image, I managed to discover a solution:

If you want to use an already-created qemu vm windows image created with `dockurr/windows` in another (new) `dockurr/windows` container, do the following:

1. It's best if you compress the windows image you've created with `dockurr/windows` into a qcow2 file.  Be sure to bring down the container, e.g. with a Ctrl-C on the `docker compose up`, and execute the following command:
```
qemu-img convert -c -O qcow2 path/to/windows/data.img some_path/my_windows_version.qcow2
```

2. Create a new `windows` directory that will be volume mounted to the `/storage` directory in your new `dockurr/windows` container, and copy your qcow2 image into it with the name `data.qcow2`:
```
cd directory_of_your_choice
mkdir windows
cp some_path/my_windows_version.qcow2 windows/data.qcow2
```

3. Then, create a symlink from file `windows/windows.boot` to `data.qcow2`:
```
cd windows
ln -s data.qcow2 windows.boot
```

4. Make sure this `windows` directory is volume-mounted to the `/storage` directory in your `compose.yml` file.  Example (provided you intend to execute `docker compose` from the directory containing the `windows` directory, `directory_of_your_choice` in this example):
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2022"  # BE SURE THIS IS SET PROPERLY
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 2222:22
    volumes:
      - ./windows:/storage  # THIS IS IMPORTANT
    restart: always
    stop_grace_period: 2m
```

5.  Run `docker compose up`, and it should boot your already-created windows image:
```
cd directory_of_your_choice
docker compose up
```
