### ISSUE TITLE
Problems when multiple docker windows instances runs simultaneously

### ISSUE THREAD

**Issue by alexunder** [dockur/windows#1287]
### Operating system

Ubuntu 24.04

### Description

I want to run about 40 instances on a server. I also want to use the different IP addresses and MAC addresses. So, I use macvlan; the only instance is okay. When I launch the second instance, the log shows below:

```bash
RTNETLINK answers: Address already in use
❯ Waiting for MAC address 02:4B:48:49:3E:AE to become available...
```

### Docker compose

```yaml
version: '3.8'

networks:
  alexander_vlan:
    external: true # 告诉Docker Compose这个网络已经存在于外部

services:

  windows-vm-01:
    image: dockurr/windows
    container_name: windows-vm-01
    environment:
      #VERSION: "10" # 或 "11"
      RAM_SIZE: "2G"
      CPU_CORES: "1"
      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 8001:8006 # VNC端口
      - 3390:3389/tcp # RDP端口
    volumes:
      - ./windows-data-01:/storage
    networks: # <--- 添加networks部分
      alexander_vlan: # <--- 引用您创建的Macvlan网络名称
        ipv4_address: 10.10.29.100 # <--- 分配唯一的静态IP地址
        mac_address: "02:42:a0:00:00:01" # <--- 分配唯一的MAC地址
    restart: always
    stop_grace_period: 2m


  windows-vm-02:
    image: dockurr/windows
    container_name: windows-vm-02
    environment:
      #VERSION: "10" # 或 "11"
      RAM_SIZE: "2G"
      CPU_CORES: "1"
      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 8002:8006 # VNC端口
      - 3391:3389/tcp # RDP端口
    volumes:
      - ./windows-data-02:/storage
    networks: # <--- 添加networks部分
      alexander_vlan: # <--- 引用您创建的Macvlan网络名称
        ipv4_address: 10.10.29.101 # <--- 分配唯一的静态IP地址
        mac_address: "02:42:a0:00:00:02" # <--- 分配唯一的MAC地址
    restart: always
    stop_grace_period: 2m
```

### Docker log

```shell
RTNETLINK answers: Address already in use
❯ Waiting for MAC address 02:4B:48:49:3E:AE to become available...
```
