### ISSUE TITLE
RDP Authentication error

### ISSUE THREAD

**Issue by CallyHam** [dockur/windows#145]
When attempting to connect to the virtual machine using microsoft remote desktop connection, i get an authentication error, i have tried using winxp, vista, win7, ltsc10, win11 as guests and they all give the same error, the container is running on my arch server and the machine i am using to connect is running Windows 10 LTSC 2021 (despite the theming), is there some sort of configuration i am missing on my windows machine or is this an issue with the container?
![Remote Desktop Connection_b1](https://github.com/dockur/windows/assets/87724457/106dc619-7ae4-420c-aa7e-f30faad2078c)
here is my current docker compose:
```yml
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ${VOLUMES_PATH}/windows/storage:/storage
    stop_grace_period: 2m
    restart: on-failure
    environment:
      VERSION: "ltsc10"
```
