### ISSUE TITLE
Help, no network in windows systemwhile creating docker container in synology

### ISSUE THREAD

**Issue by denny0810** [dockur/windows#170]
I followed the guideline to successfully create the win10 container in synology device(DSM7). docker network is defined as macvlan with fixed ipv4 address. the os can well start but there is no network inside. Yellow exclamation points shows on the network device and pci device in  Device Manager. How can I fix this problem?

**Comment by denny0810** [comment]
The docker is sticked to brigde mode. Below is the docker-compose I used to create the container. windows dirver was requested when the setup started which i select the option as " Red Hat VirtIO SCSI pass-through controller (D:\amd64\w10\vioscsi.inf)" . 
```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: win10_ltsc2019
    devices:
      - /dev/kvm
  #    - /dev/sda
  #    - /dev/sdb
    cap_add:
      - NET_ADMIN
    networks:
      macvlan_net1:
        ipv4_address: 192.168.1.120
#    ports:
#     - 8006:8006
#      - 3389:3389/tcp
#      - 3389:3389/udp
    volumes:
      - /volume1/docker/dockerWin/storage:/storage
    environment:
      VERSION: "https://example.com/win.iso"
#      MANUAL: "Y"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "64G"
#      DEVICE: "/dev/sda"
#      DEVICE2: "/dev/sdb"
    stop_grace_period: 2m
    restart: on-failure
networks:
  macvlan_net1:
    external: true
```
![image](https://github.com/dockur/windows/assets/59128785/a1d1c3c1-f474-493c-b059-afb0a14f353a)


> If you also followed the steps for DHCP=Y I think that is not supported on a Synology device because its kernel (v4) does not have the `macvtap` interface that newer Linux kernels have.
> 
> If you only did macvlan without DHCP=Y i think it should work, but maybe just stick to bridge mode because the Docker on Synology is a bit different than the normal Docker, so I cant garantuee it works.
