### ISSUE TITLE
Does this program support installation via VPS?

### ISSUE THREAD

**Issue by bywenshu** [dockur/windows#190]
I want to install Windows in my VPS（Debian 11）, and here's my docker-compose config:

```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    environment:
      VERSION: "2019"
      RAM_SIZE: "8G"
      CPU_CORES: "4"

    stop_grace_period: 2m
    restart: on-failure
```

I ran `docker ps` and I saw the container kept restarting.

The web page shows "Lost Connection".

Thanks.
