### ISSUE TITLE
Windows stuck at installer starting

### ISSUE THREAD

**Issue by youcannotseemeagain** [dockur/windows#197]
I've tried Microsoft iso and custom iso but both get stuck here.

![Snipaste_2024-](https://github.com/dockur/windows/assets/48853857/ba8f7f44-c60d-466f-b53e-3e3eddadcac8)

I've waited for several hours and it's still like this.

yml file
```
version: "3"
services:
  windows:
    image: dockurr/windows:latest
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 48080:8080
      - 48000:80
      - 44443:443
    stop_grace_period: 2m
    restart: on-failure
    environment:
      MANUAL: "N"
      VERSION: "2008"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "500G"
    volumes:
      - /home/win:/storage

```
