### ISSUE TITLE
VNC Connection Failure to VM with Custom ISO

### ISSUE THREAD

**Issue by samex** [dockur/windows#209]
Hello,

I'm encountering an issue where I cannot establish a VNC connection to a VM; the web viewer consistently reports "Failed to connect to server". Below are the details of my setup and the steps I've taken, along with the observed behavior.

**Environment:**

- Internet Connection: Poor (noted since it influenced the download of the iso)
- Operating System: Linux, Kernel version 6.7.6-arch1-2
- Docker Version: 25.0.3, build 4debf411d1
- KVM Status: Confirmed working (/dev/kvm exists and has the correct permissions, 666)

**Steps to Reproduce:**

1. Due to my poor internet connection, I used the original script's 24-hour available Microsoft URL for the ISO and downloaded it with a download manager to retrieve the VM image.
2. I placed the downloaded image (custom.iso) into /storage.
3. A script detected the image as Windows 11 and prepared the necessary files for VM creation.

**Current /storage Content:**

```
-rw-r--r-- 1 sx sx 68719476736  1. Mär 15:56 data.img
drwxrwxrwx 2 sx sx        4096  1. Mär 12:36 shared
-rw-r--r-- 1 sx sx           0  1. Mär 15:01 windows.boot
-rw-r--r-- 1 sx sx     3653632  1. Mär 12:36 windows.rom
-rw-r--r-- 1 sx sx      540672  1. Mär 15:37 windows.vars
-rw-r--r-- 1 sx sx           5  1. Mär 12:36 windows.ver
```

**Docker Logs:**
(No change even after 1 hour)

```
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,B2821E5A-7E52-42BC-9F03-DBA2248C2251,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
windows  | BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,B2821E5A-7E52-42BC-9F03-DBA2248C2251,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
```

**docker-compose.yml:**

```
version: "3"
# networks:
#   vlan:
#     external: true
services:
  windows:
    image: dockurr/windows
    container_name: windows
    privileged: true
    # networks:
    #   - vlan
    volumes:
      - ./storage:/storage
    # environment:
    #   DHCP: "Y"
    # device_cgroup_rules:
    #   - 'c *:* rwm'
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure

```

**Additional Attempts:**

- Running commands as sudo.
- Setting the container to privileged: true.

**Questions:**

Are there additional logs or diagnostics I can check to better understand the failure point?
Could the issue be related to the network setup or Docker configuration?
Is there a specific Docker or VNC viewer configuration that is known to resolve such issues?

Thank you for your assistance.
