### ISSUE TITLE
Error: dnsmasq: failed to create inotify for /etc/resolv.conf: No space left on device

### ISSUE THREAD

**Issue by SMHRambo** [dockur/windows#229]
Hello, I have tested your image, but I get the following error:

```
windows  | ❯ Extracting Windows 11 bootdisk...
windows  | ❯ Extracting Windows 11 environment...
windows  | ❯ Extracting Windows 11 setup...
windows  | ❯ Extracting Windows 11 image...
windows  | ❯ Adding XML file for automatic installation...
windows  | ❯ Building Windows 11 image...
windows  | ❯ Creating a 256G growable disk image in raw format...
windows  |
windows  | dnsmasq: failed to create inotify for /etc/resolv.conf: No space left on device
windows  | ❯ ERROR: Failed to start dnsmasq, reason: 0
windows exited with code 29
windows  |
windows  | dnsmasq: failed to create inotify for /etc/resolv.conf: No space left on device
windows  | ❯ ERROR: Failed to start dnsmasq, reason: 0
windows exited with code 29
windows exited with code 0
```

docker-compose.yml:

```
version: "3"

services:
  windows:
    image: dockurr/windows
    container_name: windows
    volumes:
      - /volume1/docker/test/app:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    environment:
      DISK_SIZE: "256G"
```
