### ISSUE TITLE
mknod: /dev/vhost-net AND mknod: /dev/net/tun   Operation not permitted 

### ISSUE THREAD

**Issue by velascog** [dockur/windows#240]
in addition 

❯ ERROR: TUN device missing. Please add the following setting to your container: --cap-add NET_ADMIN

![Screenshot 2024-03-09 06 55 35](https://github.com/dockur/windows/assets/41837548/1c0c5940-1457-47ab-95f8-48c45f89b596)

**Comment by velascog** [comment]
Installed in linux in Chromeos Flex on a Dell with an intel i5 and 100gb space (no crappy equipment).

os-version: 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


Docker version 25.0.4, build 1a576c5

I tried using both versions and both had the same result.

**Comment by velascog** [comment]
i was able to install kvm; how to add the privileged flag to the container?

**Comment by PieroSimonet** [comment]
I fixed this problem (in fedora silberblue) as follows:
first setup the devices with "modprobe tun"
second, modify the file as follows:

```
 version: "3"
services:
  windows:
    image: dockurr/windows
    environment:
      VERSION: win10
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    privileged: true
```
