### ISSUE TITLE
iptables Error

### ISSUE THREAD

**Issue by mikeleord** [dockur/windows#250]
Hello,
via portainer I used this Docker Compose:
````
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    environment:
      VERSION: "win10"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      DISK_SIZE: "32G"
      MANUAL: "Y"
    volumes:
      - /docker/win:/storage
````
but i get this error:
````
iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
❯ ERROR: Status 3 while: iptables -t nat -A POSTROUTING -o "$VM_NET_DEV" -j MASQUERADE (line 178/301)
❯ Starting Windows for Docker v2.04...
❯ For support visit https://github.com/dockur/windows
````
what can I verify?
Thank you
