### ISSUE TITLE
80 failed (97: Address family not supported by protocol)

### ISSUE THREAD

**Issue by koureni** [dockur/windows#252]
this is  **docker-compose.yml** :
```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 13389:3389/tcp
      - 13389:3389/udp
    environment:
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "100G"
      VERSION: "win11"
      stop_grace_period: 2m
      restart: on-failure
```
and when i start docker, some error below, the **docker log** showing 

```
root@mail:/app/windows# docker logs windows
❯ Starting Windows for Docker v2.04...
❯ For support visit https://github.com/dockur/windows

nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
❯ ERROR: Status 1 while: nginx -e stderr (line 166/10)

```
I have another NGINX Server using port 80 for reverse proxy, but i don't understand why docker will using port 80 also?
