### ISSUE TITLE
Initial Windows 10 allocated DISK_SIZE, doesn't change when DISK_SIZE is updated later in compose.yaml

### ISSUE THREAD

**Issue by enziaki** [dockur/windows#260]
Hey,

I initially installed Windows 10 using the script, and **allocated 100G** to the DISK_SIZE. Now that I need more storage, I updated the `compose.yaml` to **150G**, but when I checked for the space available inside of the VM, it didn't update the space available inside of the VM, as it still had my C: Drive at 100G. Am I missing something here?

I use `docker compose up -d` to start the VM.
(Please mention if there is anything else that you want)

Here is my compose.yaml:

```
version: "3"                                                                                                                        
   services:                                                                                                                           
     windows:                                                                                                                          
       image: dockurr/windows                                                                                                          
       container_name: windows                                                                                                         
       devices:                                                                                                                        
         - /dev/kvm                                                                                                                    
       cap_add:                                                                                                                        
         - NET_ADMIN                                                                                                                   
      ports:                                                                                                                          
        - 8006:8006                                                                                                                   
        - 3389:3389/tcp                                                                                                               
        - 3389:3389/udp                                                                                                               
      stop_grace_period: 2m                                                                                                           
      restart: on-failure                                                                                                             
      environment:                                                                                                                    
        VERSION: "win10"                                                                                                              
        RAM_SIZE: "8G"                                                                                                                
        CPU_CORES: "4"                                                                                                                
        DISK_SIZE: "150G"   #changed from initial 100G                                                                                                     
      volumes:                                                                                                                        
        - ./data:/storage
```

I'm running **Fedora 38** as host with kernel `Linux 6.7.7-100.fc38.x86_6` on Wayland.

Thank you.
