### ISSUE TITLE
Enable hyper-v in windows causes failure to boot

### ISSUE THREAD

**Issue by jordankoehn** [dockur/windows#265]
Hyper v within a qemu guest [should be possible](https://superuser.com/questions/1717880/how-to-enable-hyper-v-in-a-windows-guest), but causes failure to boot. I've tried to adjusting cli args for qemu to no avail. If I figure out the right combination I'll make a PR

**Comment by jordankoehn** [comment]
My apologies for not being clear. From a fresh install of windows 11, you'd [enable hyper-v](https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v) 

```powershell
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
```

Then upon reboot you're stuck in windows automatic repair. This is the same behavior with  HV=false or true in the docker env

**Comment by m4tt72** [comment]
@kroese For running WSL for example. I was trying to create a development environment on Windows & run WSL2, enabling virtualization leads to the same issue described by @jordankoehn

**Comment by bakerae493** [comment]
I experienced this issue as well... I am attempting to manage servers using hyper-v and a windows server failover cluster. Essentially looking to develop a method to manage a windows server environment from Linux, browser, etc. There may be some tools sufficient for my use, but Im in the tinkering and investigation stages here. Although nested VMs would be interesting, disregarding the challenges portrayed in Inception.

My initial thoughts were that this is blocked in qemu, since windows task manager reports that the CPU is virtualized. Passing the CPU as host or other methods to allow vt-d nested within the Docker container, within qemu, passed to windows... may be the journey.

![image](https://github.com/dockur/windows/assets/55766799/6944519e-0584-49ca-9780-3ab0c9f9898c)

Im looking forward to the development here. Thanks!

**Comment by LawrenceHwang** [comment]
I had some success with enabling nested virtualization. Got Hyper-V enabled within Windows Server 2022 VM and installed WSL (Windows for Linux Subsystem). See screenshots below.

<img width="1488" alt="Screenshot 2024-03-17 at 20 55 18" src="https://github.com/dockur/windows/assets/16510876/dec0e5f1-3c72-4a4e-a7f8-f5d4f4ae02c3">
<img width="1013" alt="Screenshot 2024-03-17 at 20 56 15" src="https://github.com/dockur/windows/assets/16510876/49dd5bb2-9123-4041-b3eb-215eb69024eb">

### Steps

1. I have Linux based host OS and enabled KVM's nested virtualization as per [doc](https://docs.fedoraproject.org/en-US/quick-docs/using-nested-virtualization-in-kvm/). Note, the steps there are CPU specific (Intel/ AMD).
2. I update the `docker-compose.yml` to include a new flag, `-cpu host` for qemu. Example:

```yaml
    entrypoint: /usr/bin/tini
    command: ["-s","--", "/run/entry.sh", "-cpu host"]
```

### Observations

I noticed during the windows vm reboot, the vm can hangs with 100% cpu utilization. I just `docker kill` and `docker start` and it came right back up.

Cheers,

L

**Comment by bakerae493** [comment]
@LawrenceHwang Would you kindly provide your docker-compose file for reference? It seems I still do not get the host cpu passthrough when adding the entrypoint commands. I may be missing something here...

I can see the CPU and nested capability within the docker container using docker exec but Windows continues to report "Virtual Machine: YES". Thus after installing Hyper-V the Windows VM would fail to boot.

Any additional information would be greatly appreciated. Thanks, Allen

**Comment by LawrenceHwang** [comment]
@bakerae493 Sure thing. The `docker-compose.yaml` is below. Have you enabled KVM's nested virtualization in the host? Here is the [doc](https://docs.fedoraproject.org/en-US/quick-docs/using-nested-virtualization-in-kvm/) applies for many Linux distro/ host. Note, the steps there are CPU specific (Intel/ AMD).

```yaml
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 33890:3389/tcp
      - 33890:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    environment:
      VERSION: "2022"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "80G"
    entrypoint: /usr/bin/tini
    command: ["-s","--", "/run/entry.sh", "-cpu host"]
    volumes:
      - storage:/storage

volumes:
  storage:
```
