### ISSUE TITLE
Connection lost after install

### ISSUE THREAD

**Issue by EHRETic** [dockur/windows#269]
Hi there,

Great project, can't wait to make it work but I've a little issue trying to deploy a system.
My host is running Almalinux 8.9, 

Here is my docker compose file:
```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: srv-test
    
    restart: on-failure

    environment:
      VERSION: "2022"
      RAM_SIZE: "8G"
      CPU_CORES: "2"
      DISK_SIZE: "128G"

    volumes:
      - system:/storage
    
    devices:
      - /dev/kvm
    
    cap_add:
      - NET_ADMIN
    
    stop_grace_period: 2m
    
    networks:
      default:
        ipv4_address: 192.168.X.X

volumes:
  system:

networks:
  default:
    external: true
    name: lan
```

The strange thing, I can see the console on port 8006 during the whole download but at the end, I get "connection lost" and nothing else happens. My macvlan works (I hope) because all my containers are configured with macvlan but it is not clear what KVM packages are required.

This is the log I can see in Portainer for this container:
```
[+] Successfully downloaded Windows image!
❯ Extracting Windows Server 2022 image...
❯ Adding XML file for automatic installation...
❯ Building Windows Server 2022 image...
❯ Creating a 128G growable disk image in raw format...
iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
❯ ERROR: Status 3 while: iptables -t nat -A POSTROUTING -o "$VM_NET_DEV" -j MASQUERADE (line 185/311)
❯ Starting Windows for Docker v2.07...
❯ For support visit https://github.com/dockur/windows
```

I tried Win 10 and it was the same result.
Any chance to help me please? Thx in advance 😉
