### ISSUE TITLE
Not working inside VM on Proxmox

### ISSUE THREAD

**Issue by crzp** [dockur/windows#273]
Hi there,
i have a Proxmox Host with different VMs.
One for my Docker containers. For this VM i enabled "nested virtualisation"

When i try to run your container it works up until the point of extracting image, or whatever the last one is before the reboot.
After that the VNC window in the browser only says "failed to connect to server" 

And then it does nothing. Just sits there.

docker compose logs:
```
❯ Starting Windows for Docker v2.07...
❯ For support visit https://github.com/dockur/windows

❯ Downloading Windows 11...
[i] Downloading Windows media from official Microsoft servers...
[i] Downloading Windows 11...
[!] Microsoft blocked the automated download request based on your IP address. Please check the FAQ on how to boot from a local file and manually download this ISO in a web browser here: https://www.microsoft.com/en-us/software-download/windows11

[!] 1 attempted download(s) failed! Please re-run Mido with these arguments to try downloading again (any partial downloads will be resumed): win11x64
[+] Finished! Please see the above errors with information
❯ Failed to download Windows 11 using Mido, will try a different method now...
❯ Downloading product information from Microsoft...
❯ Downloading Windows 11...
/storage/tmp/win11x64.esd          100%[===============================================================>]   4.54G  86.1MB/s    in 56s
❯ Extracting Windows 11 bootdisk...
❯ Extracting Windows 11 environment...
❯ Extracting Windows 11 setup...
❯ Extracting Windows 11 image...
❯ Adding XML file for automatic installation...
❯ Building Windows 11 image...
❯ Creating a 64G growable disk image in raw format...
❯ Booting Windows using QEMU emulator version 8.2.1 ...
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000007H:EDX.invtsc [bit 8]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000007H:EDX.invtsc [bit 8]
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,07522914-0A09-4EBD-B3BE-2623BFBAD596,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
```

Maybe someone has an idea of why this is happening?
Does this needs to be run on bare metal?

**Comment by crzp** [comment]
I tried win11 and win10, both with and without BOOT_MODE : "windows_plain"
Here's my compose file:

```
#version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /storage/media/windows-disk:/storage
    stop_grace_period: 2m
    environment:
      #BOOT_MODE for win11 - disables Secure Boot + TPM + Hyper-V
      BOOT_MODE: "windows_plain"
      VERSION: "win10"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"
    restart: on-failure

```
