### ISSUE TITLE
No cached windows ISOs when rebuilding docker

### ISSUE THREAD

**Issue by scherddel** [dockur/windows#283]
One of the things that bother me is that every time i change a small attribute in my docker-compose.yml it not only rebuilds everything but it also downloads the iso from MS again. Is there a way to cache the iso somehow?

**Comment by scherddel** [comment]
I've been experimenting, and it appears the issue arises when you neglect to bind the `/storage` volume to a host folder. When Docker detects changes in the compose file, it creates a new container instance with a unique ID. This fresh instance won't recognize previously downloaded Windows images.

**Comment by matifali** [comment]
Is it necessary to mount a host location to `/storage`? Can we also use a docker volume?

**Comment by matifali** [comment]
@kroese I can confirm that mounting a volume also works and persists in the storage. This works for me,

```yaml
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - storage:/storage

volumes:
  storage:
```
