### ISSUE TITLE
ERROR: Status 1 while: ip tuntap add dev "$VM_NET_TAP" mode tap (line 170/311)

### ISSUE THREAD

**Issue by alpha754293** [dockur/windows#290]
Trying to install this on my OASLOA Mini PC now (Intel N95 Processor, 16 GB LPDDR5 RAM, 512 GB NVMe SSD).

This is the error message that I get:

```
Attaching to win11
win11    | ❯ Starting Windows for Docker v2.07...
win11    | ❯ For support visit https://github.com/dockur/windows
win11    | 
win11    | ❯ Extracting local ISO image...
win11    | ❯ Detecting Windows version from ISO image...
win11    | ❯ Detected: Windows 11
win11    | ❯ Adding XML file for automatic installation...
win11    | ❯ Building Windows 11 image...
win11    | ❯ Creating a 32G growable disk image in raw format...
win11    | ❯ Installing Intel GPU drivers...
win11    | ❯ Installing OpenGL module...
win11    | open: Operation not permitted
win11    | ❯ ERROR: Status 1 while: ip tuntap add dev "$VM_NET_TAP" mode tap (line 170/311)
win11    | open: Operation not permitted
win11    | ❯ ERROR: Status 1 while: ip tuntap add dev "$VM_NET_TAP" mode tap (line 170/311)
win11 exited with code 1
win11    | open: Operation not permitted
win11    | ❯ ERROR: Status 1 while: ip tuntap add dev "$VM_NET_TAP" mode tap (line 170/311)
win11 exited with code 1
win11    | open: Operation not permitted
win11    | ❯ ERROR: Status 1 while: ip tuntap add dev "$VM_NET_TAP" mode tap (line 170/311)
win11 exited with code 1
```

Here is my `docker-compose.yml` file:

```
version: "3"
services:
  win11:
    image: dockurr/windows
    container_name: win11
    devices:
      - /dev/kvm
      - /dev/dri
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "32G"
      GPU: "Y"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./win11:/storage
    security_opt:
      - apparmor:unconfined
    sysctls:
      net.ipv4.ip_forward: 1
    networks:
      vlan:
        ipv4_address: 172.168.0.143
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure

networks:
  vlan:
    external: true
```

Not really sure why this doesn't work on my Intel N95 mini PC, but it seems to work just fine with my 5950X system.

(The setup is effectively identical between the two system, other than the fact that my Mini PC doesn't have a 3090 being that it's a 0.34L Mini PC. Both systems are running Proxmox as the hypervisor. Both systems are running an Ubuntu 20.04 LTS LXC container as the basis for the test platform.)

Thanks.
