### ISSUE TITLE
Windows could not apply unattended settting during pass [OfflineServicing]. - exception during installation

### ISSUE THREAD

**Issue by vetl12** [dockur/windows#299]
Hello I'm trying to install win11 docker image however getting the above mentioned error. I tried to disable few things but still it gives me the same error. Could you please help out ? This happens with win 10 image and the other ones as well. 

docker run
  -d
  --name='WindowsinDocker'
  --net='bridge'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="MATRIX"
  -e HOST_CONTAINERNAME="WindowsinDocker"
  -e 'VERSION'='win11'
  -e 'CPU_CORES'='2'
  -e 'RAM_SIZE'='12G'
  -e 'DISK_SIZE'='64G'
  -e 'DHCP'='N'
  -e 'MANUAL'='Y'
  -e 'TPM'='N'
  -e 'HV'='N'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8006]'
  -l net.unraid.docker.icon='https://github.com/dockur/windows/raw/master/.github/logo.png'
  -p '8007:8006/tcp'
  -p '3389:3389/tcp'
  -v '/mnt/cache/appdata/WindowsinDocker/':'/storage':'rw'
  --device='/dev/kvm'
  --cap-add=NET_ADMIN
  --stop-timeout=120
  --device-cgroup-rule='c *:* rwm' 'dockurr/windows' 

BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)

![image](https://github.com/dockur/windows/assets/163923090/2ca71b09-a767-4d4f-ab73-3ec8d44349f7)

**Comment by vetl12** [comment]
Ha it did pick u the flag now ( before i deleted only .iso file not the whole folder). however not its throws this error :/
![image](https://github.com/dockur/windows/assets/163923090/07b78331-d24f-4777-acd5-9f7cbc82e7ac)

**Comment by vetl12** [comment]
> From the message it looks like the downloaded ISO file is corrupted somehow? Never seen it before!

sorry for the late reply. Yeah, message is weird, and it happened few times. Does it matter the file system that docker is on ? i.e. my docker is running in Unraid server on disk partition in BTRFS. not sure if internally in container would be different file system.

**Comment by vetl12** [comment]
> No, it should not matter. Did you manage to solve it already?

nope =( tried deleting everything and re-running, with same results.

**Comment by passtpro** [comment]
Good afternoon. I am getting the same error shown in the first post of this thread. I am using the UnRaid Community App and have not made any changes to the default settings. I have tried both the Windows 11 and Windows 10 images. On initial run I get the original error, then after a reboot I get a "Recovery" screen (see attachment). 
![image](https://github.com/dockur/windows/assets/73154528/1d38bcba-770e-4ac9-a8e3-a2236dfeb0fb)

**Comment by passtpro** [comment]
> @passtpro When you add a container variable with the key `MANUAL` and the value `Y` does it allow you to complete the installation manually? Because that may help to diagnose why the automatic one fails.

Sorry for the late response. I am trying this today and will report the results.

**Comment by passtpro** [comment]
Completely wiped it all out, followed manual install selecting the correct storage driver, and now I get an error about a missing, required driver.

**Comment by Sociopathssive** [comment]
Having the same issue in Unraid with the WindowsinDocker from the CA store. Tried with default settings, WIN10, Server2022 and Server2019. Starting fresh with including wiping appdata and image each with each version. Stating the "... unattend during pass.."  and BSOD recovery.

**Comment by Sociopathssive** [comment]
> I noticed that everyone who has this problem are all users of unRaid / WindowsInDocker CA? So my guess is that it may have something to do with the filesystem for example. Maybe it only happens on ZFS disks for storage, and thats why it does not happen on other Linux distros?
> 
> So my suggestion would be to try if using a another filesystem makes a difference? (On unRaid you can switch between FUSE and native by using `/mnt/cache/` instead of `/mnt/user` for example. Or if you have a EXT4 partition to use that one).
> 
> Other suggestion would be to play with the disk parameters via container variables, for example:
> 
> Set `DISK_FMT` to `qcow2` instead of `raw`. Or set `ALLOCATE` to `Y` instead of `N`. Or set `DISK_IO` to `threads` and `DISK_CACHE` to `writeback`.
> 
> The difficulty for me is that when everybody just say "I am having the same issue", while nobody is listing their machine specs (like filesystem, cpu model, etc) it is impossible to detect a pattern what you all share in common. If everyone who reports it is using BTRFS filesystem or is using the same CPU, it would be much easier to figure out it was a problem with BTRFS for example.

Specs:

Model: | R720XD
-- | --
M/B: | Dell Inc. 0C4Y3R Version A02
BIOS: | Dell Inc. Version 2.9.0 Dated 12/06/2019
CPU: | Intel® Xeon® CPU E5-2667 v2 @ 3.30GHz
HVM: | Enabled
IOMMU: | Enabled
Cache: | Not Specified: 256 KiB, Not Specified: 2 MiB, Not Specified: 25 MiB, Not Specified: 256 KiB, Not Specified: 2 MiB, Not Specified: 25 MiB
Memory: | 192 GiB DDR3 Multi-bit ECC (max. installable capacity 1536 GiB)
Network: | bond0: adaptive load balancing, mtu 1500
Kernel: | Linux 6.1.79-Unraid x86_64

Appdata FS : BTRFS on PCIe Gen3 NVMe

**Comment by Sociopathssive** [comment]
> Does one of you happen to have any partitions that are not BTRFS in your unRaid? To see if it makes a difference when the storage path is on a different filesystem?
> 
> Or otherwise try changing it from `/mnt/cache` to `/mnt/user` so that even though its still on BTRFS it goes through the FUSE layer.

Testing some different FS now:
So far it boots in ZFS off a USB SDD, mounted in unassigned devices( quick and dirty). Looking to test more when I have time.

Container:
![image](https://github.com/dockur/windows/assets/8444236/99dc272b-dc17-4e96-8d55-d9dc623632ee)

ZFS "pool":
![image](https://github.com/dockur/windows/assets/8444236/964baea2-e1db-4dd8-8ac6-1f6af1b36bea)

![image](https://github.com/dockur/windows/assets/8444236/422337a1-b027-4509-8cce-09384dfb13a4)

**Comment by GiuffreLab** [comment]
Building containers based on the image tag 3.08 seems to cause this issue now on a system that I previously did not see this on.

Rolling images back to 3.07 resolved the error message. Not sure what changed, but 3.08 has some problems with this.

**Comment by passtpro** [comment]
@kroese Been a while since I responded, but wanted to follow up. I was able to get everything installed once I changed my cache disk to ZFS. Looks like the standard install does not play well with BTRFS.

**Comment by GiuffreLab** [comment]
> @GiuffreLab Can you provide some more info, like the Windows version you are installing, on which filesystem, etc?

Docker node is bare a metal Debian server latest release, file systems ext4 and was tested against win11 and 2022 Windows Versions.

**Comment by GiuffreLab** [comment]
@kroese Sorry, been tied up all day. Here is two examples of how I was deploying. These work when I change the image to `dockurr/windows:3.07`. In this state last I tried a few days ago (day of update), they failed. This is exactly how they were deployed, aside from `credentials` and the full `volume` path changing.

Apologies for the over commenting, I keep archives of working docker compose files, and it helps me not have to remember why I did things the way they are.

## Single Node Deployment
``` yaml
version: "3.8"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: win11 # win11e, win11, win10e, win10, win8, win8e, win7, vista, winxp, 2022, 2019, 2016, 2012, 2008
      DISK_SIZE: 128G # 64G is the minimum - This is how much space the windows system drive can use as needed on the host
      CPU_CORES: 4 # 2 cores is the minimum
      RAM_SIZE: 8G # 4G is the minimum
      USERNAME: <CHANGEME>
      PASSWORD: <CHANGEME>
    volumes:
      - ./windows-test/shared:/shared # shared folder between host and container
      - ./windows-test/var/win:/storage # windows system drive
    devices:
      - /dev/kvm # this is for the ability to see the windows build screen via VNC web interface on port 8006
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006 # this is the port for VNC web interface 
      - 3389:3389/tcp # this is the port for RDP
      - 3389:3389/udp # this is the port for RDP
    stop_grace_period: 2m
    restart: unless-stopped
```

## Multi-Node Deployment
``` yaml
version: "3.8"
services:
  windows:
    image: dockurr/windows:3.07
    container_name: windows
    environment:
      VERSION: win11 # win11e, win11, win10e, win10, win8, win8e, win7, vista, winxp, 2022, 2019, 2016, 2012, 2008
      DISK_SIZE: 128G # 64G is the minimum - This is how much space the windows system drive can use as needed on the host
      CPU_CORES: 4 # 2 cores is the minimum
      RAM_SIZE: 8G # 4G is the minimum
      USERNAME: <CHANGEME>
      PASSWORD: <CHANGEME>
    volumes:
      - ./windows-test/shared:/shared # shared folder between host and container
      - ./windows-test/var/win:/storage # windows system drive
    devices:
      - /dev/kvm # this is for the ability to see the windows build screen via VNC web interface on port 8006
      - /dev/vhost-net
    device_cgroup_rules:
      - c *:* rmw
    cap_add:
      - NET_ADMIN
    networks:
      vlan:
        ipv4_address: 192.168.10.56 # this is the IP address of the container on the network - must be in the range of the subnet below
    ports:
      - 8006:8006 # this is the port for VNC web interface
      - 3389:3389/tcp # this is the port for RDP
      - 3389:3389/udp # this is the port for RDP
    stop_grace_period: 2m
    restart: unless-stopped
  windows-svr:
    image: dockurr/windows:3.07
    container_name: windows-svr
    environment:
      VERSION: 2022 # win11e, win11, win10e, win10, win8, win8e, win7, vista, winxp, 2022, 2019, 2016, 2012, 2008
      DISK_SIZE: 128G # 64G is the minimum - This is how much space the windows system drive can use as needed on the host
      CPU_CORES: 4 # 2 cores is the minimum
      RAM_SIZE: 8G # 4G is the minimum
      USERNAME: <CHANGEME>
      PASSWORD: <CHANGEME>
    volumes:
      - ./windows-test/shared:/shared # shared folder between host and container
      - ./windows-test/var/win:/storage # windows system drive
    devices:
      - /dev/kvm # this is for the ability to see the windows build screen via VNC web interface on port 8006
      - /dev/vhost-net
    device_cgroup_rules:
      - c *:* rmw
    cap_add:
      - NET_ADMIN
    networks:
      vlan:
        ipv4_address: 192.168.10.57 # this is the IP address of the container on the network - must be in the range of the subnet below
    ports:
      - 8006:8006 # this is the port for VNC web interface
      - 3389:3389/tcp # this is the port for RDP
      - 3389:3389/udp # this is the port for RDP
    stop_grace_period: 2m
    restart: unless-stopped
networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0 # this is the physical network interface on the host docker is running on
    ipam:
      config:
        - subnet: 192.168.10.0/24
          ip_range: 192.168.10.56/29 # this is the usable range of IP addresses that can be assigned to containers - 192.168.10.56-62
          gateway: 192.168.10.1
```
