### ISSUE TITLE
Giving error when passing "environment" option to compose.

### ISSUE THREAD

**Issue by MubinMuhammad** [dockur/windows#307]
After giving the adding `environment: VERSION: "win7"` to docker it gives me this error: `PATH_TO_GIT_REPO/docker-compose.yml: (root) Additional property environment is not allowed`. Here's the docker-compose file if needed:
``` yaml
version: "3"

services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure

environment:
  VERSION: "win7"
```

I don't have any experience with docker. So, this might be a pretty silly mistake. Please don't get angry if so.

Thanks.
