### ISSUE TITLE
How to connect to a HTTP service inside windows VM from another container

### ISSUE THREAD

**Issue by ravintrmedia** [dockur/windows#321]
I can RDP to windows (port 3389) and also connect to the desktop via the web interface too (port 8006). However I cannot curl into a HTTP service running on a different port (eg. port 8000) in Windows from another docker container on the same network. I assume the dockur windows container must forward the traffic into the qemu windows VM running inside it. But I don't know how to get it working.

My setup is:
- Dockur windows container (this is using Tiny11 image)
   - There's a HTTP service listening on port 8000 in windows.
   - In windows firewall, port 8000 is open.
   - If I do `curl http://localhost:8000` within windows powershell, it gives the 200 OK response as expected.
   - Docker inspect of this container shows network alias `windows`
- Curl container name: **mycurl**
   - I'm running `curl http://windows:8000/` in this container.
   - `curl http://windows:8006` gives a HTML page `301 Moved Permanently` status. I assume this is from the web interface service so I know curl is working here.
   - `curl http://windows:8000` just hangs. The request does not hit my HTTP service in windows.

Both containers are part of the same docker network called `tiny11b_default`

Curl container start command: `docker run --rm -it --name mycurl --network tiny11b_default curlimages/curl bash`

Dockur windows docker-compose.yml
```
version: "3"
services:
  windows:
    image: dockurr/windows
    environment:
      DISK_SIZE: "25G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    volumes:
      - ./storagedir:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8000:8000
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
```

Is there something I'm doing wrong? Should I somehow add a port forwarding rule inside the dockur windows container to passthrough my port 8000?

Thank you for this great project. Everything was seamless so far for me except this HTTP service scenario. Thank you.
