### ISSUE TITLE
Kubernetes ?

### ISSUE THREAD

**Issue by fliot** [dockur/windows#341]
First of all this project sounds promising.

I may be kilometers away, because even if I'm tiny KVM/QEMU user, I'm clearly out regarding drivers/docker capabilities involved...
By advance, sorry if this issue is beyond supported use cases.

I try to use  **dockurr/windows:latest** on my K3S Kubernetes cluster (linux based).

My environment:
```
$> kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
```

Do I have a chance to make it run ?

I created such deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  template:
    spec:
      containers:
        - image: dockurr/windows:latest
          imagePullPolicy: IfNotPresent
          name: windows
          ports:
            - containerPort: 8006
              name: vnc
              protocol: TCP
            - containerPort: 3389
              name: rdp-tcp
              protocol: TCP
            - containerPort: 3389
              name: rdp-udp
              protocol: UDP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_BIND_SERVICE
                - NET_BROADCAST
                - NET_RAW
                - AUDIT_CONTROL
                - FOWNER
                - MKNOD
                - SETGID
                - SYS_CHROOT
                - AUDIT_WRITE
                - DAC_OVERRIDE
                - FSETID
                - KILL
                - SETPCAP
                - SETFCAP
                - SETUID
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /storage
              name: matlab-windows
            - mountPath: /dev/kvm
              name: kvm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/lib/rancher/k3s/storage/bind-mount-matlab-windows
            type: Directory
          name: matlab-windows
        - hostPath:
            path: /dev/kvm
            type: CharDevice
          name: kvm
```

On run, I get this :
```
Container: windows
Filter
Disconnected
❯ Starting Windows for Docker v2.08...
❯ For support visit https://github.com/dockur/windows

2024-04-04T16:24:12.949854390Z RTNETLINK answers: File exists
❯ ERROR: Failed to create bridge. Please add the following setting to your container: --cap-add NET_ADMIN
```

Thanks by advance for any inputs.
Best regards.
