### ISSUE TITLE
How to set password on novnc?

### ISSUE THREAD

**Issue by WaltonThompson** [dockur/windows#343]
Hello team,

can you help me I am using your docker image to run Windows container but when I see no password protected by default can you help me which file or environment variable set to enable password protection on vnc connect time.

**Comment by kroese** [comment]
This is now implemented, you can set:

```yaml
environment:
  PROTECT: "Y"
  USERNAME: "bill"
  PASSWORD: "gates"
```

to set authentication for the VNC website.
