### ISSUE TITLE
RDP connection when running in WSL2

### ISSUE THREAD

**Issue by Zenthae** [dockur/windows#345]
Hello,
I'm running the following in a WSL2 Ubuntu instance, I wonder if it's possible to connect to it with RDP client.
When i use `localhost:3390` to connect, i get an error telling me that it can't connect.

<details>
<summary>Error</summary>

[Window Title]
Remote Desktop Connection

[Content]
This computer can't connect to the remote computer.

Try connecting again. If the problem continues, contact the owner of the remote computer or your network administrator.

[^] Hide details  [OK]

[Expanded Information]
Error code: 0x904
Extended error code: 0x7
Timestamp (UTC): 04/05/24 09:33:19 AM

Press Ctrl+C to copy.

</details>

```yml
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "winxp"
    volumes:
      - win_xp:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3390:3389/tcp
      - 3390:3389/udp
    stop_grace_period: 2m
    restart: on-failure

volumes:
  win_xp:
```
