### ISSUE TITLE
virtIO-win Ethernet Adapter assigning conflicting IP address

### ISSUE THREAD

**Issue by gavO852** [dockur/windows#365]
I have a quite specific issue that has popped up after spinning up a Windows Server 2022 container in my homelab, specifically that the RedHat VirtIO Ethernet Driver seems to be assigning a DHCP address for the internal container that just so happens to also line up with one of my VLANs (20.20.20.0/24) in my local network that need to access the resource. The following is my compose file for the container, manually assigning the container itself the IP address in VLAN 2 (27.50.50.0/24).

```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "22"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"
      MANUAL: "Y"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    networks:
      vlan:
        ipv4_address: 27.50.50.243

networks:
  vlan:
      external: true
```
**_Windows Server 2022: Terminal ipconfig:_**
![windows-server](https://github.com/dockur/windows/assets/35172725/1b5f0b15-a1bb-4ed4-89ff-4d57b7302245)
**_Container's Shell ipconfig:_**
![container](https://github.com/dockur/windows/assets/35172725/cd99ec8c-f9c5-4951-b658-b91c31eaf54d)

After going through the manual installation process, setting up Windows, I noticed that the ethernet driver is assigning Windows an IP address of 20.20.20.21. However, when I change this via ncpa.cpl to another IP range that doesn't conflict with my VLANs, the VM is no longer accessible via RDP, only through QEMU VNC in the browser at port 8006. Research online has led to inconclusive results about how to customize the IP range the driver is assigning to Windows. Is there any way that I can change this range during the installation process to avoid the range overlap? 

Please let me know if this is the wrong place to be asking this, I figured it would be the best place to start asking for help. Thanks in advance! :)
