### ISSUE TITLE
Windows cannot read the <ProductKey> setting from the unattend answer file

### ISSUE THREAD

**Issue by peteythepanda** [dockur/windows#393]
**compose.yaml:**
```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://drive.massgrave.dev/en-us_windows_10_iot_enterprise_ltsc_2021_x64_dvd_257ad90f.iso"
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      DIZK_SIZE: "120G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - ./data:/storage
~                                              
```
![Screenshot 2024-04-17 at 22-08-11 QEMU (windows) - noVNC](https://github.com/dockur/windows/assets/93201801/c0c22738-8421-4729-94ca-9dcbe84a1068)
