### ISSUE TITLE
How to make this windows container able to ping other docker container via name?

### ISSUE THREAD

**Issue by mpinque** [dockur/windows#396]
### Question

I have two containers (1 redis and this Windows 11). I joined their networks together using networks in the docker-compose file.

In the Redis container, I can ping Windows container via name and IP without an issue.

```
root@ee69b877e806:/data# ping windows
PING windows (172.24.0.2) 56(84) bytes of data.
64 bytes from windows.redis_network (172.24.0.2): icmp_seq=1 ttl=64 time=0.111 ms
64 bytes from windows.redis_network (172.24.0.2): icmp_seq=2 ttl=64 time=0.105 ms
^C
--- windows ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1017ms
rtt min/avg/max/mdev = 0.105/0.108/0.111/0.003 ms
root@ee69b877e806:/data# ping redis
PING redis (172.24.0.3) 56(84) bytes of data.
64 bytes from ee69b877e806 (172.24.0.3): icmp_seq=1 ttl=64 time=0.010 ms
64 bytes from ee69b877e806 (172.24.0.3): icmp_seq=2 ttl=64 time=0.052 ms
```

Pinging by name in the Windows container to Redis doesn't work. But you can ping the IP address of the Redis container

![image](https://github.com/dockur/windows/assets/6471620/c88051ca-a6aa-4671-b359-579e44718d92)

I wonder how ping via name in this Windows container to other containers would work?

Please help and thank you.

**The Windows container IP details**

```
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Red Hat VirtIO Ethernet Adapter
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 20.20.20.21(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Wednesday, April 17, 2024 6:44:59 AM
   Lease Expires . . . . . . . . . . : Sunday, May 25, 2160 10:09:42 AM
   Default Gateway . . . . . . . . . : 20.20.20.1
   DHCP Server . . . . . . . . . . . : 20.20.20.1
   DNS Servers . . . . . . . . . . . : 20.20.20.1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

**The docker-compose files**
_For Windows_ 

```
services:
  windows:
    #privileged: true
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      RAM_SIZE: "32G"
      CPU_CORES: "4"
      DISK_SIZE: "100G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    stop_grace_period: 2m
    volumes:
      - ./win:/storage
    restart: on-failure
    networks:
      - network
networks:
  network:
    name: redis_network
    external: true

```

_For Redis_

```
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/dаta:/root/redis
    environment:
      - REDIS_PASSWORD=27GByAnB1LNulN5tk31rL
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - network
networks:
  network:
    driver: bridge
    name: redis_network
```

The output of the docker inspect network

```
[
    {
        "Name": "redis_network",
        "Id": "d8ae2287b3a570434ff241601aeb384a6715a16fcc47182d3d6acc38168a28c9",
        "Created": "2024-04-16T16:28:53.790996323+10:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.24.0.0/16",
                    "Gateway": "172.24.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "2fc0c90339bb52eab9391e57a90bf14f2a82e7daa176ddafe32464c07b9f9bf9": {
                "Name": "windows",
                "EndpointID": "0633bee282b60fddaf014902429f36e7a41f0e2f98327c19e206da4674ba4ce7",
                "MacAddress": "02:42:ac:18:00:02",
                "IPv4Address": "172.24.0.2/16",
                "IPv6Address": ""
            },
            "ee69b877e806c70c1c3139d378f1028092788d4b8c6788dfce5c234b444210cd": {
                "Name": "redis",
                "EndpointID": "ed40b88220030cbdb38470adcf1ab4dd614708297acf75ff1fd3428215540480",
                "MacAddress": "02:42:ac:18:00:03",
                "IPv4Address": "172.24.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "network",
            "com.docker.compose.project": "redisprod",
            "com.docker.compose.version": "2.25.0"
        }
    }
]
```
