### ISSUE TITLE
Installing Duo RDP broke the RDP connection

### ISSUE THREAD

**Issue by mpinque** [dockur/windows#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Machine specifications

Intel Xeon-E 2388G - 8c/16t - 3.2 GHz/4.6 GHz / 128G RAM

### Operating system

Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64)

### Docker version

Docker version 26.0.0, build 2ae903e

### Description

Everything was working in terms of application software installations, joining the machine to the domain etc.
But after I installed the Duo Authentication for Windows Logon and RDP https://duo.com/docs/rdp, I eventually got disconnected from my RDP session and couldn't connect anymore.

- I have tried rebooting the machine
- Ping the internal IP of the machine from another container which works
- Telneting port 3939 via internal docker IP which doesn't work.

I'm not sure if the machine booted after the reboot because I cannot access it via port 8007 for VNC. The VNC page loaded but it cannot connect.

What can be done to troubleshoot this?

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: windowsmachine
    environment:
      VERSION: "win11"
      RAM_SIZE: "32G"
      CPU_CORES: "4"
      DISK_SIZE: "200G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      #  - "5986:5986/tcp"
      - "8007:8006"
      - "3939:3389/tcp"
      - "3939:3389/udp"
    stop_grace_period: 2m
    volumes:
      - ./win:/storage
    restart: on-failure
    networks:
      - network
networks:
  network:
    name: redis_network
    external: true
```

### Docker log

```
BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,E1F8427D-9498-4E69-BFAB-9BC1EC0E887F,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
windowsmachine  | BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,E1F8427D-9498-4E69-BFAB-9BC1EC0E887F,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
```
