### ISSUE TITLE
Windows 11 pro 23H2 cannot connect with rdp when using

### ISSUE THREAD

**Issue by vsnote** [dockur/windows#430]
### Question

**os version:** 22631.3527

**docker compose:**
```yml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "winxp"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3390:3389/tcp
      - 3390:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - /e/sys-image/winxp3.iso:/storage/custom.iso
```

**Is this question related to wsl？**
![image](https://github.com/dockur/windows/assets/8895379/6f07b348-5ad9-42bc-88b8-9e09fe7b691b)

![image](https://github.com/dockur/windows/assets/8895379/465d2a07-c35f-44c3-938d-6010c6ae0798)
