### ISSUE TITLE
When installing winxp in windows 11, you cannot use rdp to connect to winxp in docker

### ISSUE THREAD

**Issue by vsnote** [dockur/windows#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Machine specifications

Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz   2.90 GHz / 16.0 GB

### Operating system

Windows 11 Pro

### Docker version

Docker Desktop 4.29.0 (145265)

### Description

Winxp is installed successfully, http://localhost:8006 can also be connected normally, but cannot be connected using rdp

### Docker compose

```yml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "winxp"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3390:3389/tcp
      - 3390:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - /e/sys-image/winxp3.iso:/storage/custom.iso
```

### Docker log

no output

### Screenshots (optional)

![image](https://github.com/dockur/windows/assets/8895379/d75f4606-cdb0-433f-981e-8715deff74f4)
![image](https://github.com/dockur/windows/assets/8895379/94dbadb4-0481-4052-a87f-61b526581964)
