### ISSUE TITLE
[Bug]: winget upgrade failed

### ISSUE THREAD

**Issue by yongjer** [dockur/windows#437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Machine specifications

intel 11900F 32G

### Operating system

Ubuntu 2204 / 6.5.0-28-generic

### Docker version

Docker version 26.1.0, build 9714adc

### Description

running ```winget upgrade --all```
then error occurs:
```
Failed when searching source: winget
0x8a15000f : Data required by the source is missing
```

### Docker compose

```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    volumes:
      - /home/yongjer/windows/Win11_23H2_Chinese_Traditional_x64v2.iso:/storage/custom.iso
    devices:
      - /dev/kvm
    environment:
      RAM_SIZE: "16G"
      CPU_CORES: "4"
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure


### Docker log

```
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,FBCB37C9-FC18-496F-A7C0-8D572A9FE7CC,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
windows  | BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,FBCB37C9-FC18-496F-A7C0-8D572A9FE7CC,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
windows  | ❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
```

### Screenshots (optional)

![螢幕快照 2024-04-29 21-53-22](https://github.com/dockur/windows/assets/54315206/b7d4df7f-1144-4611-a2cd-fa0fc1741f9b)
