### ISSUE TITLE
[Bug]: win11 won't boot

### ISSUE THREAD

**Issue by dingetje** [dockur/windows#449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Machine specifications

Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 2803 Mhz, 4 Core(s), 8 Logical Processor(s)/ 32GB RAM

### Operating system

Linux LT-ANTOINEM 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Docker version

Docker version 26.0.0, build 2ae903e

### Description

Using a Win11, x64 as host, the script fails to boot win11 to completion

### Docker compose

docker run -it --rm --name windows -p 8006:8006 --device=/dev/kvm --cap-add NET_ADMIN --stop-timeout 120 -e BOOT_MODE=windows_plain dockurr/windows

### Docker log

?

### Screenshots (optional)

![image](https://github.com/dockur/windows/assets/609871/a1044d3c-6e53-4253-84ed-3057a9bf19c2)

**Comment by thetredev** [comment]
You could also increase your WSL system's RAM in your `.wslconfig` file in your Windows home directory, assuming your machine has enough RAM to begin with.

**Comment by OlivierArgentieri** [comment]
I think i got the same issue.

## Environment:

- Ryzen 9 3950X
- 128G RAM
- Windows 10 22h2 19045.3930
- WSL2

I'm trying to run it without kvm



## Docker compose
```yml
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      KVM: "N"
      CONSOLE: "Y"
      CPU_CORES:  "8" # I also tried to remove quotes char
      DISK_SIZE: "100G"
      RAM_SIZE: "8G"
      HV: "N" # I tried to remove it also
      BOOT_MODE: "windows_plain" # i also try with UEFI
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
```

## Result

![image](https://github.com/dockur/windows/assets/30509073/182d9748-d6a6-48a3-93ae-b25cac7a77ef)

![image](https://github.com/dockur/windows/assets/30509073/b90652ba-6294-408c-8116-f26af9f6e230)


Tell me if it's not related to this issue.
