### ISSUE TITLE
[Question]: "/dev/kvm" Device Error on Docker for Windows After System Reinstall

### ISSUE THREAD

**Issue by JRLK0** [dockur/windows#456]
### Question

**Context:**
I've recently reinstalled Windows on my machine, which is equipped with a 13th generation Intel processor. Previously, my Docker setup worked seamlessly, including the use of the `/dev/kvm` device for virtualization purposes. However, after reinstalling the OS, using the same Docker configuration and without any apparent changes to the system hardware or basic settings, I encounter an issue.

**Summary of the Problem:**
Post-reinstallation, an error occurs stating that the custom device `/dev/kvm` cannot be added due to the "no such file or directory" issue. This problem was not present before reinstalling Windows. I suspect this might relate to a configuration setting in Windows that was not exactly replicated from the previous installation, or it could be due to updates in the recent versions of Docker or Windows that are affecting this behavior.

**Docker Compose Configuration Used:**
```yaml
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure

```
**Steps to Reproduce the Issue:**

Create the docker-compose.yml file with the above content.
Execute the command: docker compose -f "docker-compose.yml" up -d --build
Operating System and Docker Version:

Versión de WSL: 2.1.5.0
Versión de kernel: 5.15.146.1-2
Versión de WSLg: 1.0.60
Versión de MSRDC: 1.2.5105
Versión de Direct3D: 1.611.1-81528511
Versión DXCore: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Versión de Windows: 10.0.19045.4355

Docker Version: Docker Desktop 4.29.0 (145265) is currently the newest version available.

Question:
Has anyone else experienced this issue, or does anyone have suggestions on how to resolve the /dev/kvm error when running Docker on Windows? Could this issue be related to specific configurations or updates in Windows or Docker?

Additional Information:
Any other information that might be relevant to understanding the context and the problem.

Thank you in advance for any help or suggestions you can provide.
