### ISSUE TITLE
[Question]: DHCP Not Working

### ISSUE THREAD

**Issue by softplaceio** [dockur/windows#487]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

Hello, 
My container with W11Pro not working DHCP.
I'm configure something wrong?
Thanks !

```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: W11Pro
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "120G"
      DHCP: "Y"
    devices:
      - /dev/kvm
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
```
