### ISSUE TITLE
[Question]: How do I specify an IP to Windows?

### ISSUE THREAD

**Issue by Southseast** [dockur/windows#507]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

This is a similar question in the [FAQ](https://github.com/dockur/windows?tab=readme-ov-file#how-can-windows-acquire-an-ip-address-from-my-router), but I want to specify an IP to Windows instead of DHCP. What should I do?

**Comment by Southseast** [comment]
When I use `macvlan` mode with `DHCP=Y` and enter `ipconfig` on the cmd, it is shown as follows.

```
C:\Users\Docker\Desktop>ipconfig

Windows IP Configuration


Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::4192:558f:7082:a7b1%12
   IPv4 Address. . . . . . . . . . . : 172.22.108.102
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 172.22.108.254

Tunnel adapter isatap.{167133D2-1830-4B68-A65C-1A019F1A5D7B}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
```

So I use `netsh interface ip set address "Ethernet" static 172.22.108.75 255.255.255.0 172.22.108.254` to modify the network configuration. But now it shows "no internet access" and I can't connect Windows via RDP.

**Comment by Southseast** [comment]
And this is my docker-compose.yml

```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      DHCP: "Y"
    volumes:
      - ./2012.iso:/storage/custom.iso
      - ./storage:/storage
    devices:
      - /dev/kvm
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c *:* rwm'
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
    networks:
      vlan:
        ipv4_address: 172.22.108.98
        
networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: ens33
    ipam:
      config:
        - subnet: "172.22.108.0/24"
          ip_range: "172.22.108.0/24"
          gateway: "172.22.108.254"
```
