### ISSUE TITLE
[Question]: Mounting WinPE ISO and Working on Installed OS Drive

### ISSUE THREAD

**Issue by WSHAPER** [dockur/windows#509]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### TL;DR

I'm seeking guidance on whether it's possible to mount a WinPE ISO and work on a drive containing an already installed OS, specifically to create an image with prepackaged software after running sysprep on the previously installed OS contained in `storage/`.

Could you please advise on the following:
1. Is it possible to mount a WinPE ISO and work on the drive containing the installed OS as described?
2. If so, what changes or additional configurations are required to achieve this?

Thank you for your assistance in advance!

### Setup

Here is my `storage/` directory structure:
```bash
[4.0K]  ./
├── [4.0K]  shared/
│   └── [ 566]  readme.txt*
├── [   0]  boot.iso*
├── [ 64G]  data.img*
├── [2.9G]  HBCD_PE_x64.iso*
├── [  18]  windows.mac*
├── [   4]  windows.old
├── [3.5M]  windows.rom*
├── [528K]  windows.vars*
└── [   5]  windows.ver*
```

I've attempted the following `compose.yml` configuration, but it results in the Windows logo appearing without booting into WinPE:
```yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
      BOOT_INDEX: "1"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - ~/github/windows/storage/HBCD_PE_x64.iso:/storage/boot.iso
      - ~/github/windows/storage:/storage
```

**Comment by WSHAPER** [comment]
First of all, thank you for the quick response for taking the time to resolve my question!

### Clarification

Apologies for the confusion, I was indeed switching between `qemu-docker` and `docker-windows`.

- `HBCD_PE_x64.iso` refers to [Hiren's Boot CD](https://www.hirensbootcd.org/), a bootable toolkit based on `WinPE`
- `boot.iso` comes from an attempt to map `HBCD_PE_x64.iso` as the boot drive in `compose.yml`
    ```yaml
    volumes:
      - ~/github/windows/storage/HBCD_PE_x64.iso:/storage/boot.iso
    ```

### Steps to Reproduce

1. **Download** `tiny11_2311_x64.iso` manually
2. **Rename** `tiny11_2311_x64.iso` to `custom.iso` and **place** in `storage/`
    - Alternatively, map to location directly as suggested in the [README.md (line 156)](https://github.com/dockur/windows/edit/master/readme.md#L156)
3. **Update** `compose.yml`:
    - Map `storage/`
    - Map `win11x64.xml` (unattended install)
      ```yaml
      volumes:
        - ~/github/dockur-windows/storage:/storage
        - ~/github/dockur-windows/assets/win11x64.xml:/run/assets/win11x64.xml
      ```
4. **Remove** the following from `compose.yml`:
    ```yaml
    environment:
          VERSION: "win11"
    ```
5. **Let installation complete after running**:
    ```bash
    docker-compose up -d
    ```
6. **Inspect** via `localhost:8006` and **shut down** after install with:
    ```bash
    docker-compose down
    ```
      - After installation, your `storage/` should look like this (`custom.iso` now missing):
        ```bash
        [4.0K]  ./
        ├── [4.0K]  shared/
        │   └── [ 566]  readme.txt
        ├── [ 64G]  data.img
        ├── [   0]  windows.boot
        ├── [  18]  windows.mac
        ├── [3.5M]  windows.rom
        ├── [528K]  windows.vars
        └── [   5]  windows.ver
        ```

> In a comment on [Issue #362 (Boot from ISO After Installation)](https://github.com/dockur/windows/issues/362#issuecomment-2048110260), you suggested setting `BOOT_INDEX` environment variable to a value lower than 3.

7. **Modify** `compose.yml` and **run** `docker-compose up -d`:
    - Set `BOOT_INDEX`
    - Attempt to map `HBCD_PE_x64.iso` to `custom.iso`
      ```yaml
      environment:
            BOOT_INDEX: "1"
      volumes:
        # Add:
        - ~/path/to/your/file/HBCD_PE_x64.iso:/custom.iso
        # Keep:
        - ~/github/dockur-windows/storage:/storage
        # Remove:
        # - ~/github/dockur-windows/assets/win11x64.xml:/run/assets/win11x64.xml
      ```

8. **Encounter** the following error during boot splash screen, regardless whether `BOOT_INDEX` was `1` or `2`:
    ```plaintext
    BdsDxe: failed to load Boot0001 "UEFI QEMU QEMU CD-ROM" from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0):
       Not Found
    BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,C12D7E12-7880-4EB6-9122-11802D87CCBD,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
    BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,C12D7E12-7880-4EB6-9122-11802D87CCBD,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
    ```

**Comment by WSHAPER** [comment]
First of all, thank you for the quick response for taking the time to resolve my question.
I've retried the entire procedure documented below and got the bootable `.iso` running.
However, I'm still not certain on how to properly map the installed partition, so it's visible in the bootable WinPE's `diskmgmt.msc`.

### Clarification

Apologies for the confusion, I was indeed switching between `qemu-docker` and `docker-windows`.

- `HBCD_PE_x64.iso` refers to [Hiren's Boot CD](https://www.hirensbootcd.org/), a bootable toolkit based on `WinPE`
  - Any bootable media can be substituted here.
- `boot.iso` comes from an attempt to map `HBCD_PE_x64.iso` as the boot drive in `compose.yml`
    ```yaml
    volumes:
      - ~/github/windows/storage/HBCD_PE_x64.iso:/storage/boot.iso
    ```

### Steps to Reproduce

1. **Download** `tiny11_2311_x64.iso` manually
2. **Rename** `tiny11_2311_x64.iso` to `custom.iso` and **place** in `storage/`
    - Alternatively, map to location directly as suggested in the [README.md (line 156)](https://github.com/dockur/windows/edit/master/readme.md#L156)
3. **Update** `compose.yml`:
    - Map `storage/`
    - Map `win11x64.xml` (unattended install)
      ```yaml
      volumes:
        - ~/github/dockur-windows/storage:/storage
        - ~/github/dockur-windows/assets/win11x64.xml:/run/assets/win11x64.xml
      ```
4. **Remove** the following from `compose.yml`, since [`src/install.sh:195`](https://github.com/dockur/windows/blob/master/src/install.sh#L195) seems to match `custom.iso`:
    ```yaml
    environment:
          VERSION: "win11"
    ```
5. **Let installation complete after running**:
    ```bash
    docker-compose up -d
    ```
6. **Inspect** via `localhost:8006` and **shut down** after install with:
    ```bash
    docker-compose down
    ```
      - After installation, your `storage/` should look like this (`custom.iso` now missing):
        ```bash
        [4.0K]  ./
        ├── [4.0K]  shared/
        │   └── [ 566]  readme.txt
        ├── [ 64G]  data.img
        ├── [   0]  windows.boot
        ├── [  18]  windows.mac
        ├── [3.5M]  windows.rom
        ├── [528K]  windows.vars
        └── [   5]  windows.ver
        ```

> In a comment on [Issue #362 (Boot from ISO After Installation)](https://github.com/dockur/windows/issues/362#issuecomment-2048110260), you suggested setting `BOOT_INDEX` environment variable to a value lower than 3.

7. **Modify** `compose.yml` and **run** `docker-compose up -d`:
    - Set `BOOT_INDEX`
    - Attempt to map `HBCD_PE_x64.iso` to `custom.iso`
      ```yaml
      environment:
            BOOT_INDEX: "1"
      volumes:
        # Add:
        - ~/path/to/your/file/HBCD_PE_x64.iso:/storage/custom.iso
        # Keep:
        - ~/github/dockur-windows/storage:/storage
        # Remove:
        # - ~/github/dockur-windows/assets/win11x64.xml:/run/assets/win11x64.xml
      ```

8. **Open** `localhost:8006` and run `diskmgmt.msc` inside the bootable WinPE `.iso`, where only the `virtio-win-0.1.248` shows up, not the drives created in previous installation.
