### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by EHRETic** [dockur/windows#531]
### Is there no existing feature request for this?

- [X] I have searched the existing feature requests

### Is your proposal related to a problem?

Not a problem

### Describe the solution you'd like.

Hi there,

First, lovely concept, I use it to test a few things and I find it amazing :-)

I have a question/probably a feature request for multiple interfaces : is it possible to have a macvlan IP in network **macvlan_A** and the Windows docker to have an interface (IP with DHCP or fixed) in a **macvlan_B**

What I plan : secure the VNC on port 8006 behind a reverse proxy on a subnet dedicated to containers and have my Windows server on my normal LAN.

Both macvlan A & B are available on the host with multiple VLANs/docker networks.

Thanks in advance for your answer!

### Describe alternatives you've considered.

For now on, I use 2 different IPs in the same subnet, but I can't secure VNC on my LAN because it is not behind my firewall/reverse proxy.

**Comment by EHRETic** [comment]
> So instead of a macvlan A and macvlan B, it currently works as macvlan A and macvtap B.

This is what I'm using currently, but that would more compare to something like macvlan A & macvtap A no?
(as macvtap is bridged to macvlan if I understood correctly)

What I would like to be able to do is:
- macvlan A interface vlan123 with IP 192.168.123.X (/24)
- macvlan B interface vlan234 with IP 192.168.234.Y (/24)

2 completely different subnets linked to 2 different macvlan interfaces.
 
(don't worry, I can live without, but that could be a nice addition)

**Comment by EHRETic** [comment]
Hi,

I just tried and I soon as I change my macvlan, the VM interface is also switched to the same subnet (confirmed by DHCP)
This confirms my theory of macvtap is bridged to the macvlan interface (but remains a separate one)

Would be a nice addition, but if I'm the only one requesting it... well... 😊

**Comment by EHRETic** [comment]
> I will see if I can add dual macvlan in the future, but it wont be anytime soon.

I would scale it straight to "multiple" ! 😊

**Comment by EHRETic** [comment]
Hi @kroese 😊

Was the idea abandonned or will it be integrated in a future version?
I didn't found anything in releases notes...

PS: I don't see any link "releases" at the right bar of https://github.com/dockur/windows/ repository :

![image](https://github.com/user-attachments/assets/db2c3b11-2627-43dd-815a-f8ca6d5312a6)

But it is available at macos one... any chance to add it again?

![image](https://github.com/user-attachments/assets/3896f118-4c81-4cf5-b3f9-a0a2b9439464)

**Comment by EHRETic** [comment]
Hi,

I think I missed how to configure 2 interfaces somehow... and as I need to rebuild some VMs from scratch to use thin provisioned disks, I'll take the opportunity to configure them with KVM + Windows interfaces.

Any advice to modify the following configuration?
(for now, the IP is for the KVM and VM uses DHCP option, but both are on the same network)

Thanks! 😊

Config:
```yaml
services:
  windows:
    image: dockurr/windows
    container_name: srv-test
    
    restart: unless-stopped

    environment:
      VERSION: '${VERSION}'
      RAM_SIZE: '${RAM_SIZE}'
      CPU_CORES: '${CPU_CORES}'
      DISK_SIZE: '${DISK_SIZE}'
      DHCP: '${DHCP}'

    volumes:
      - system:/storage
      - data:/storage2
    
    devices:
      - /dev/kvm
      - /dev/vhost-net

    device_cgroup_rules:
      - 'c *:* rwm'
    
    cap_add:
      - NET_ADMIN
    
    stop_grace_period: 2m
    
    networks:
      default:
        ipv4_address: 192.168.X.X

volumes:
  system:
  data:

networks:
  default:
    external: true
    name: my_lan
```
