### ISSUE TITLE
Forcefully terminating Windows, reason: 0..

### ISSUE THREAD

**Issue by lasharor** [dockur/windows#538]
### Is there no existing issue for this?

- [X] I have searched the existing issues

### Machine specifications

13th Gen Intel Core TM i5 13500 | RAM: 11/32 GB | DISK: 119 GB (zfs) | HOST:

### Operating system

 6.5.13-5-pve, docker on LXC Debian, KVM passthrough enabled and verified

### Docker version

Docker version 20.10.24+dfsg1, build 297e128

### Description

Trying to run this on my config. I tried many different things including many of those that are listed in the issues here on github. I tried enabled "CONSOLE" but it doesn't give any additional information. So, I don't know what to change. 

Tried: enabled/disabling GPU, enabling/disabling KVM, changing from windows 11 to 11. enabled passhtrough of vhost-net, verified kvm via kvm-ok, installed relevant KVM/qemu packages

### Docker compose

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
      GPU: "Y"
      CONSOLE: "Y"
    devices:
      - /dev/dri
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8033:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
    - /var/lib/docker/volumes/windows:/storage
    sysctls:
    - net.ipv4.ip_forward=1

### Docker log

❯ Starting Windows for Docker v3.10...
❯ For support visit https://github.com/dockur/windows
❯ CPU: 13th Gen Intel Core TM i5 13500 | RAM: 11/32 GB | DISK: 119 GB (zfs) | HOST: 6.5.13-5-pve...
❯ Installing Intel GPU drivers...
❯ Installing OpenGL module...
❯ Booting Windows...
3h3h3hBdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
❯ ERROR: Forcefully terminating Windows, reason: 0...
3h❯ Shutdown completed!

**Comment by lasharor** [comment]
Like this compose file: 

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      HV: "N"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8033:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
    - /docker/windows:/storage
    sysctls:
    - net.ipv4.ip_forward=1
```

Still the same problem, builds the images. Seems to boot and then immediatly shutsdown.
