### ISSUE TITLE
[Issue]: Can't login into windows

### ISSUE THREAD

**Issue by iamarpitpatidar** [dockur/windows#540]
### Is there no existing issue for this?

- [X] I have searched the existing issues

### Machine specifications

4 GB Memory / 2 Intel vCPUs / 120 GB Disk

### Operating system

Ubuntu 22.04

### Docker version

Docker version 26.1.1, build 4cf5afa

### Description

upon provision getting this error

> the referenced account is currently locked out and may not be logged into

### Docker compose

```yaml
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      RAM_SIZE: "2G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - ./data:/storage
```

### Docker log

BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,D8C4569A-1E96-42AC-95A1-BE1F2FAF0B0D,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,D8C4569A-1E96-42AC-95A1-BE1F2FAF0B0D,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

### Screenshots (optional)

![Screen Shot 2024-05-25 at 1 52 50 PM](https://github.com/dockur/windows/assets/44097148/becb1a0e-c951-41b4-b04a-83b423f2f061)
