### ISSUE TITLE
[Bug]: Error while smbd booting 

### ISSUE THREAD

**Issue by flt6** [dockur/windows#559]
### Operating system

Ubuntu 22.04.4 LTS

### Description

run `docker-compose up`

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "winxp"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```

### Docker log

```
 Starting Windows for Docker v3.11...
❯ For support visit https://github.com/dockur/windows
❯ CPU: 12th Gen Intel Core TM i7 12700 | RAM: 12/16 GB | DISK: 749 GB (fuseblk) | HOST: 6.5.0-35...

❯ Downloading Windows XP from bobpony.com...
❯ ERROR: Failed to download https://dl.bobpony.com/windows/xp/professional/en_windows_xp_professional_with_service_pack_3_x86_cd_x14-80428.iso , reason: 8
❯ Failed to download Windows XP, will try another mirror now...
❯ Downloading Windows XP from files.dog...

     0K ........ ........ ........ ........  5% 1.38M 6m43s
 32768K ........ ........ ........ ........ 10% 1.69M 5m46s
 65536K ........ ........ ........ ........ 16% 1.75M 5m11s
 98304K ........ ........ ........ ........ 21% 1.75M 4m44s
131072K ........ ........ ........ ........ 27% 1.62M 4m24s
163840K ........ ........ ........ ........ 32% 1.59M 4m5s
196608K ........ ........ ........ ........ 38% 1.79M 3m42s
229376K ........ ........ ........ ........ 43% 1.62M 3m23s
262144K ........ ........ ........ ........ 48% 1.53M 3m5s
294912K ........ ........ ........ ........ 54% 1.65M 2m45s
327680K ........ ........ ........ ........ 59% 1.61M 2m26s
360448K ........ ........ ........ ........ 65% 1.72M 2m6s
393216K ........ ........ ........ ........ 70% 1.75M 1m45s
425984K ........ ........ ........ ........ 76% 1.58M 86s
458752K ........ ........ ........ ........ 81% 1.83M 66s
491520K ........ ........ ........ ........ 86% 1.73M 47s
524288K ........ ........ ........ ........ 92% 1.80M 27s
557056K ........ ........ ........ ........ 97% 1.88M 8s
589824K ........ .....                     100% 1.69M=5m52s

❯ Extracting Windows XP image...
❯ Adding drivers to image...
❯ Building Windows XP image...
❯ Warning: the filesystem of /storage is FUSE, this extra layer will negatively affect performance!
❯ Resizing disk from 5G to 64G...
ERROR: Can't log to stdout (-S) unless daemon is in foreground (-F) or interactive (-i)
❯ ERROR: Status 1 while: smbd --debug-stdout (line 73/18)

```
