### ISSUE TITLE
Windows won't install with an USB device connected 

### ISSUE THREAD

**Issue by luisgmuniz** [dockur/windows#563]
### Operating system

Fedora 39

### Description

In the compose file I have added an USB device (a card reader).
_If the USB device is connected_ then the first time I boot the image (that is, Windows has yet to be installed) it won't install ("Windows could not clean disk 0.  The specified disk does not exist. [...]")
This does not happen if the os is already installed, or it has to be installed but the USB device is not connected.

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win81e"
      ARGUMENTS: "-device usb-host,vendorid=0x0bda,productid=0x0169"  # DNIe reader
    devices:
      - /dev/kvm
      - /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ./iso/win81x64-enterprise-eval.iso:/custom.iso        # ISO
```

### Docker log

Starting Windows for Docker v3.05...
For support visit https://github.com/dockur/windows
CPU: Intel Core TM i5 10210U CPU | RAM: 9/16 GB | DISK: 26 GB (ext4) | HOST: 6.8.10-200.fc39.x86_64...

Extracting local ISO image...
Detecting version from ISO image...
Detected: Windows 8 Enterprise (Evaluation)
Adding win81x64-enterprise-eval.xml for automatic installation...
Building Windows 8 image...
Creating a 64G growable disk image in raw format...
Booting Windows...
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
Windows started succesfully, visit http://localhost:8006/ to view the screen...

### Screenshots (optional)

![windows-could-not-clean-disk-0](https://github.com/dockur/windows/assets/2011450/681306fe-bac2-4433-a394-e9d3c95eaafb)
