### ISSUE TITLE
Can only use USB passthru with privileged container

### ISSUE THREAD

**Issue by nodecaf** [dockur/windows#584]
### Operating system

Fedora 40

### Description

When I tried to get either a usb serial device or usb storage drive to be accessible from Win10 container, I could only do so using privileged container mode. 

Btw, other than that I have to say I'm very impressed with the project! well done!

### Docker compose
```yaml
services:
  windows:
    volumes:
      - /win:/storage
      - "/media/shared:/shared"
    image: dockurr/windows
    container_name: windows
    environment:
       VERSION: "win10"
       ARGUMENTS: "-usb -device usb-host,vendorid=0x1a86,productid=0x7523"
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/bus/usb
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    privileged: true
    userns_mode: 'host'
```

### Docker log

❯ Starting Windows for Docker v3.11...                                                                                                        20:08:47 [0/446]
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Core TM i7 5600U CPU | RAM: 8/16 GB | DISK: 106 GB (btrfs) | HOST: 6.8.10-300.fc40.x86_64...
                                                                       
❯ Booting Windows...     
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,05A4D071-897C-4FCC-BC78-133FB60B3DE5,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,05A4D071-897C-4FCC-BC78-133FB60B3DE5,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
qemu-system-x86_64: libusb_release_interface: -4 [NO_DEVICE]
❯ Received SIGTERM, sending ACPI shutdown signal...
❯ Waiting for Windows to shutdown... (1/110)         
❯ Waiting for Windows to shutdown... (2/110)                           
❯ Shutdown completed!
