### ISSUE TITLE
Windows XP in Russian language installation issues

### ISSUE THREAD

**Issue by arisudesu** [dockur/windows#592]
### Operating system

Alpine Linux 3.20

### Description

1. A product key entry appears during install. It doesn't appear in english (default) language. Russian windows doesn't accept the key you provide in define.sh.
  Screenshot 1: it tells "Invalid product key entered".
  It accepts the key that is published on massgrave site for WinXP VL x86, however, if manually typed. Then installation proceeds.

2. WSH error happens during "Registring components" phase. The error tells: "Username not found" (screenshot 2). After I click "OK", installation proceeds to completion and booting to installed OS, but only to tell "Logon is not possible. Check username and domain and repeat password entry. Passwords are case-sensitive." (screenshot 3). 
   After clicking "OK" it reverts to modern logon screen with Administrator account available. It is possible to logon with password from compose file into it. The system looks usable except missing drivers for VGA and PCI and SM buses.

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "winxp"
      LANGUAGE: "ru"
#      CPU_CORES: 4
#      RAM_SIZE: 2G
      USERNAME: "arisu"
      PASSWORD: "1234"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```

### Docker log

```
SeaBIOS (version 1.16.3-debian-1.16.3-2)
Booting from Hard Disk...
```
(yes this is complete output from `docker logs windows`)

### Screenshots (optional)

![изображение](https://github.com/dockur/windows/assets/6342849/0699ad24-5646-406d-a48e-d977fa04838d)
![изображение](https://github.com/dockur/windows/assets/6342849/d80fc31f-f30f-493b-bdf8-8840cf8bae9c)
![изображение](https://github.com/dockur/windows/assets/6342849/d9bfd983-d571-45a3-aec9-13a90ea33267)
![изображение](https://github.com/dockur/windows/assets/6342849/2ace62a1-d29d-43bd-a6b2-3bbb53564a42)
