### ISSUE TITLE
[Question]: qemu return error while booting windows

### ISSUE THREAD

**Issue by WaterFishJ** [dockur/windows#595]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

❯ Extracting Windows 10 image...
❯ Adding drivers to image...
❯ Adding win10x64.xml for automatic installation...
❯ Building Windows 10 image...
❯ Creating a 128 growable disk image in raw format...
❯ Booting Windows...
❯ ERROR: qemu-system-x86_64: -device scsi-hd,drive=data3,bus=data3b.0,channel=0,scsi-id=0,lun=0,rotation_rate=1,bootindex=3: Cannot get 'write' permission without 'resize': Image size is not a multiple of request alignment

**Comment by WaterFishJ** [comment]
My docker-compose.yml:
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
      LANGUAGE: "Chinese"
      RAM_SIZE: "3G"
      CPU_CORES: "4"
      USERNAME: "waterfishj"
      PASSWORD: "waterfishj"
      DISK_SIZE: "128"
    devices:
      - /dev/kvm
    volumes:
      - /home/waterfishj/docker_compose/windows/data/storage1:/storage
      - /home/waterfishj/docker_compose/windows/data/shared:/shared
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```
