### ISSUE TITLE
Connectivity/Network problem from within the container

### ISSUE THREAD

**Issue by gillesperrin** [dockur/windows#612]
### Operating system

macOS 14.5 23F79 (M3 max)

### Description

Output connection is not working, ping is ok but not telnet

### Docker compose

```
version: "3.8"
services:
  windows:
    container_name: windows
    image: dockurr/windows
    privileged: true
    volumes:
      - ./data:/shared
    environment:
      KVM: "N"
      VERSION: "winxp"
      REGION: "fr-FR"
      KEYBOARD: "fr-FR"
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
```

### Docker log

```
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
```

### Screenshots (optional)

<img width="1510" alt="image" src="https://github.com/dockur/windows/assets/509125/c7312a0b-7a13-447b-9cc1-2244dcf25589">
