### ISSUE TITLE
Add archive.org download URL for Tiny10/11

### ISSUE THREAD

**Issue by geckolinux** [dockur/windows#629]
### Operating system

Debian 12

### Description

Hi there, first of all thanks for this extremely useful project.

I'm not sure if it's something intermittent, or a permanent problem in my geographical location, or a general issue for most users, but for me the downloads for Tiny10/11 from cnxiaobai.com are coming in at just a few kilobytes per minute. It appears that the official download location for those ISOs is archive.org, which manages a decent ~500KB/sec.

Thanks a lot!

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: Tiny11
    environment:
      VERSION: "tiny11"
      DISK_FMT: "qcow2"
    volumes:
      - /home/myself/.var/VMs/Tiny11:/storage
      - /home/myself/Desktop:/shared
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    privileged: true
    stop_grace_period: 2m
```

### Docker log

```
❯ Starting Windows for Docker v3.12...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Core TM i7 9750H CPU | RAM: 23/32 GB | DISK: 278 GB (btrfs) | HOST: 6.1.0-22-amd64...

❯ Downloading Tiny 11 from cnxiaobai.com...
```

(It's so slow that it's not even showing the download progress)
