### ISSUE TITLE
failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found

### ISSUE THREAD

**Issue by geekyouth** [dockur/windows#65]
# docker-compose.yaml
```
version: "3.9"

services:
  win10:
    image: dockurr/windows:1.09
    hostname: win10
    container_name: win10-dev
    stop_grace_period: 2m
    restart: unless-stopped
    environment:
      VERSION: "https://example.com/win10.iso"
      #VERSION: "win10"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "100G"
      MANUAL: "Y"
      TZ: Asia/Shanghai
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - ./_docker-data/w10/storage:/storage

```

# error log

```
[+] Running 1/1
 ✔ Container win10-dev  Started                                                                                                                                                                                                                                                                                     0.0s
win10-dev  | ❯ Starting Windows for Docker v1.09...
win10-dev  | ❯ For support visit https://github.com/dockur/windows
win10-dev  |
win10-dev  | ❯ Creating a growable disk image in raw format with a size of 100G...
win10-dev  | ❯ Booting Windows using QEMU emulator version 8.1.2 ...
win10-dev  |
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
win10-dev  | BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
win10-dev  | BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
win10-dev  |
Press any key to boot from CD or DVD......




BdsDxe: failed to start Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0): Time out
win10-dev  | BdsDxe: loading Boot0003 "EFI Internal Shell" from Fv(7CB8BDC9-F8EB-4F34-AAEA-3EE4AF6516A1)/FvFile(7C04A583-9E3E-4F1C-AD65-E05268D0B4D1)
win10-dev  | BdsDxe: starting Boot0003 "EFI Internal Shell" from Fv(7CB8BDC9-F8EB-4F34-AAEA-3EE4AF6516A1)/FvFile(7C04A583-9E3E-4F1C-AD65-E05268D0B4D1)
win10-dev  |
UEFI Interactive Shell v2.2
win10-dev  | EDK II
win10-dev  | UEFI v2.70 (Debian distribution of EDK II, 0x00010000)
win10-dev  | Mapping table
win10-dev  |       FS0: Alias(s):CD0a0b:;BLK2:
win10-dev  |           PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)/CDROM(0x1)
win10-dev  |       FS1: Alias(s):F0a0:;BLK3:
win10-dev  |           PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)/VenMedia(C5BD4D42-1A76-4996-8956-73CDA326CD0A)
win10-dev  |      BLK4: Alias(s):
win10-dev  |           PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
win10-dev  |      BLK0: Alias(s):
win10-dev  |           PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
win10-dev  |      BLK1: Alias(s):
win10-dev  |           PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)/CDROM(0x0)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
^Ccanceled

```

# file tree
```
# tree
.
├── docker-compose.yaml
└── _docker-data
    └── w10
        └── storage
            ├── data.img
            ├── win10.iso
            ├── windows.rom
            └── windows.vars
```
