### ISSUE TITLE
Always stuck on page "Setup is starting"

### ISSUE THREAD

**Issue by knisz** [dockur/windows#652]
### Operating system

CentOS Linux release 7.9.2009 (Core)

### Description

I use this docker-compose.yml
```
 version: "3"
 services:
   windows:
     image: dockurr/windows
     container_name: windows
     devices:
       - /dev/kvm
     volumes:
       - ./storage:/storage
     cap_add:
       - NET_ADMIN
     ports:
       - 8006:8006
       - 3389:3389/tcp
       - 3389:3389/udp
     stop_grace_period: 2m
     environment:
       VERSION: "ltsc10"
       RAM_SIZE: "8G"
       CPU_CORES: "16"
       DISK_SIZE: "128G"
       HV: "N"
       BOOT_MODE: "windows_plain"
     restart: always
```
now have this error:
```
#  docker logs --tail 100 -f windows
❯ Starting Windows for Docker v3.12...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon CPU E5 2696 v3 | RAM: 11/16 GB | DISK: 265 GB (xfs) | HOST: 3.10.0-1160.92.1.el7.x86_64...

❯ Booting Windows securely using QEMU v8.2.4...

BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)


❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
```
when I open chrome with the url, I only can see "Setup is starting" in screen(I wait a lot of hours). what can I do ? thanks!

### Docker compose

 version: "3"
 services:
   windows:
     image: dockurr/windows
     container_name: windows
     devices:
       - /dev/kvm
     volumes:
       - ./storage:/storage
     cap_add:
       - NET_ADMIN
     ports:
       - 8006:8006
       - 3389:3389/tcp
       - 3389:3389/udp
     stop_grace_period: 2m
     environment:
       VERSION: "ltsc10"
       RAM_SIZE: "8G"
       CPU_CORES: "16"
       DISK_SIZE: "128G"
       HV: "N"
       BOOT_MODE: "windows_plain"
     restart: always

### Docker log

❯ Starting Windows for Docker v3.12...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon CPU E5 2696 v3 | RAM: 11/16 GB | DISK: 265 GB (xfs) | HOST: 3.10.0-1160.92.1.el7.x86_64...

❯ Booting Windows securely using QEMU v8.2.4...

BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)

❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

### Screenshots (optional)

<img width="1045" alt="2024-07-17 103631" src="https://github.com/user-attachments/assets/e9885921-d301-4bc5-b750-c68617c20374">
