### ISSUE TITLE
docker compose error

### ISSUE THREAD

**Issue by sojab0on** [dockur/windows#675]
### Operating system

ubuntu 22.04.1 LTS

### Description

when running a docker compose file with the basics on this git hub it errors on running 

The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'windows'

### Docker compose

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

### Docker log

have no logs the container is not created due to the unsiported error in the compose file it self

**Comment by sojab0on** [comment]
Strange thing was its directly copy from the code page with the copy button

only ting i did was nano docker-compose.yml pasted in that and save it

**Comment by sojab0on** [comment]
I run 2.28.1-1 of docker compose plugin and 1.25.0-1 of compose it self  (there is no newer version in the repo of ubuntu ) in ubuntu 22.04.1 lts
if i put the version line on top it 
/usr/local/bin/docker-compose: line 1: Not: command not found

**Comment by gylfirst** [comment]
You need to have the volumes and all under the 'windows' service:
```
version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows10
    environment:
      VERSION: win10
      language: Dutch
    volumes:
      - /var/win:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```
You can check [docker compose documentation](https://docs.docker.com/compose/compose-application-model/).

Hope that it helps you.
