### ISSUE TITLE
Stuck on a boot circle (Win10)

### ISSUE THREAD

**Issue by MMaaxx3253** [dockur/windows#688]
### Operating system

Ubuntu 22.04.4 LTS

### Description

When i starting it i noticed that windows 10 is getting stuck on a boot circle
Also one detail, my server doesnt have kvm (no file /dev/kvm), but when i type `lscpu | grep 'Virtualization'` it shows me
`Virtualization type:                full`
So, can someone say how to fix that?
Also, windows 10 1809 works well but RDP is not working (black screen)

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
      LANGUAGE: "Russian"
      RAM_SIZE: "14G"
      CPU_CORES: 4
      USERNAME: "MakeMeButter"
      KVM: "N"
    devices:
      - /dev/net/tun
      - /dev/full
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ~/composer/data:/storage
      - ~/composer/shared:/shared
```

### Docker log

❯ Starting Windows for Docker v3.12...
❯ For support visit https://github.com/dockur/windows
❯ CPU: Intel Xeon Platinum 8259CL CPU | RAM: 54/63 GB | DISK: 22 GB (ext4) | HOST: 6.5.0-1020-aws...

❯ Requesting Windows 10 in Russian from Microsoft server...
❯ Downloading Windows 10 in Russian...

download log here :)

❯ Extracting Windows 10 image...
❯ Adding drivers to image...
❯ Adding win10x64.xml for automatic installation...
❯ Building Windows 10 image...
❯ Creating a 64G growable disk image in raw format...
❯ Booting Windows using QEMU v8.2.4...
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU CD-ROM " from PciRoot(0x0)/Pci(0x5,0x0)/Scsi(0x0,0x0)
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
❯ Received SIGTERM, sending ACPI shutdown signal...
❯ Cannot send ACPI signal during Windows setup, aborting...
❯ ERROR: Forcefully terminating Windows, reason: 143...
qemu-system-x86_64: terminating on signal 15 from pid 61 (bash)

### Screenshots (optional)

what should i put here? a circle?
