### ISSUE TITLE
[Question]: Unraid App Store Image Indicates no BTRFS support. Is this still true?

### ISSUE THREAD

**Issue by te5s3rakt** [dockur/windows#720]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

Only just getting back to playing around with this container and noted that the Unraid App Store Image details says:

> IMPORTANT: Does not work with BTRFS filesystems on Unraid. See the FAQ on the Github page for support.

Checking the FAQ page in this repo though, there's no such mention.

Is this still an issue?

Reason I ask, is my Unraid box has:
- Array of 6 x HDDs formatted as XFS -- My Bulk Storage
- Pool of 2 x NVMe in RAID1 formatted as BTRFS -- My App Cache
- Pool of 1 x SATA SSD formatted as BTRFS -- My Write Cache

Ideally I don't really want to run my Windows "VM" from the slower bulk storage, as I run any "apps" from the NVMe pool.

Thanks

**Comment by aligator** [comment]
Just an Idea and for me the installation worked with that on a btrfs:

Since this is using images heavily, you should disable COW.

To do this 
* Create a storage folder `mkdir storage`
* Execute `chattr +C storage`
* mount the storage into docker:
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./storage:/storage
    stop_grace_period: 2m
```
https://wiki.archlinux.org/title/Btrfs#Disabling_CoW
Also this is hinted as warning in this section:
https://wiki.archlinux.org/title/QEMU#Creating_a_hard_disk_image

Could this be tested by someone else?
