### ISSUE TITLE
XP: Line 27 of the INF file Vi386\winnt.sif is invalid

### ISSUE THREAD

**Issue by dmlogv** [dockur/windows#735]
### Operating system

Debian GNU/Linux 12

### Description

Thank you for the great project.

I've tried to install the Windows XP but after the inspecting of the hardware configuration I get an error:

```
Line 27 of the INF file Vi386\winnt.sif is invalid
Setup cannot continue. Press any key to exit.
```

After restarting it repeats of course.

(I've started from the Russian image and locale, and also tested using the default compose — the same result.)

### Docker compose

```yaml
services:
  windows:
    image: dockurr/windows
    container_name: winxp
    environment:
      VERSION: "winxp"
      
      #LANGUAGE: "Russian"
      #REGION: "ru-RU"
      #KEYBOARD: "ru-RU"
      
      RAM_SIZE: "1G"
      CPU_CORES: "1"
      DISK_SIZE: "10G"
      
      USERNAME: "Dmitry"
      PASSWORD: "${PASSWORD}"
      
    volumes:
      - ${APPDATA}/winxp:/storage
    devices:
      - /dev/kvm
    #cap_add:
    #  - NET_ADMIN
    ports:
      - 8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```

### Docker log

```
DSsDSsDSsDSs                                     
SeaBIOS (version 1.16.3-debian-1.16.3-2)         
Booting from Hard Disk...                        
Boot failed: not a bootable disk                 

Booting from DVD/CD...  
```
