### ISSUE TITLE
[Question]: How to run multi windows?

### ISSUE THREAD

**Issue by eovipmak** [dockur/windows#739]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

Hello,

I'm trying to run multi container, each container run 1 windows version. Like container 1 runs windows 10, container 2 runs windows 11, etc...

Can someone show me the ways? Thank

Best Regard.

**Comment by U-L-M-S** [comment]
Well... I think I understand your question. To make it possible you have 2 options.

# Option A
Run a single docker compose and separate each windows in different services (This way u can start all 3 windows in the same time).

`docker-compose up -d`

Your docker-compose.yml should looks kinda like this:
(make sure to set unique container_name for each of them and the ports)
```
services:
  windows11:
    image: dockurr/windows
    container_name: windows11
    environment:
      VERSION: "win11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

  windows10:
    image: dockurr/windows
    container_name: windows10
    environment:
      VERSION: "win10"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8007:8007
      - 3390:3389/tcp
      - 3390:3389/udp
    stop_grace_period: 2m

  windows7:
    image: dockurr/windows
    container_name: windows7
    environment:
      VERSION: "win7"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8008:8008
      - 3391:3389/tcp
      - 3391:3389/udp
    stop_grace_period: 2m
```

# Option B
Create 3 docker-compose.yml files, each with a sevice like showing up and build each with `docker compose up -d`
