### ISSUE TITLE
[Bug]: Password Protection doesn't work.

### ISSUE THREAD

**Issue by Dethkiller15** [dockur/windows#748]
### Operating system

Ubuntu 24.04.1 LTS

### Description

I set up USERNAME and PASSWORD along with CUSTOM_USER(as some containers use that for novnc) in the environment variables set up and loaded it up.... no username or password required to get in at all. No prompt just instant access.(I have it secured to just LAN IPs and 1 IP on the outside for when I am out and about via reverse proxy.)

### Docker compose

CasaOS ComposeFile
```
name: windows
services:
  windows-10:
    cap_add:
      - NET_ADMIN
    cpu_shares: 90
    command: []
    container_name: Windows-10
    deploy:
      resources:
        limits:
          memory: 28972M
    devices:
      - /dev/kvm:/dev/kvm
    environment:
      - CUSTOM_USER=SomeUsername
      - PASSWORD=SlightlySecurePass
      - USERNAME=SomeUsername
      - VERSION=win10
    hostname: Windows-10
    image: dockurr/windows:latest
    labels:
      icon: https://cdn1.iconfinder.com/data/icons/operating-system-flat-1/30/windows_10-512.png
    ports:
      - mode: ingress
        target: 8006
        published: "8006"
        protocol: tcp
    restart: on-failure
    stop_grace_period: 2m0s
    volumes:
      - type: bind
        source: /DATA/AppData/Windows 10
        target: /storage
        bind:
          create_host_path: true
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: SomeURLNotNeeded.com
  icon: https://cdn1.iconfinder.com/data/icons/operating-system-flat-1/30/windows_10-512.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: https
  store_app_id: windows
  title:
    custom: Windows 10

```

### Docker log

As Shown in the command "docker logs Windows-10" in cockpit terminal
![image](https://github.com/user-attachments/assets/a29da2a0-aa40-4832-8777-58055615dfc2)
```
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,BCF6F541-B2FA-4D61-8AD1-37CF0F177F91,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,BCF6F541-B2FA-4D61-8AD1-37CF0F177F91,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
```

As shown in CasaOS
```
Windows-10  | ❯ Starting Windows for Docker v3.17...
Windows-10  | ❯ For support visit https://github.com/dockur/windows
Windows-10  | ❯ CPU: AMD Ryzen 7 5700U | RAM: 26/29 GB | DISK: 77 GB (ext4) | HOST: 6.8.0-45...
Windows-10  | 
Windows-10  | [1;31m❯ Warning: unexpected clocksource: hpet[0m
Windows-10  | [1;34m❯ [1;36mBooting Windows using QEMU v9.0.2...[0m
Windows-10  | [2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01HBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,BCF6F541-B2FA-4D61-8AD1-37CF0F177F91,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
Windows-10  | BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,BCF6F541-B2FA-4D61-8AD1-37CF0F177F91,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
Windows-10  | [1;34m❯ [1;36mWindows started succesfully, visit http://localhost:8006/ to view the screen...[0m
Windows-10  | ❯ Shutdown completed!
Windows-10  | ❯ Starting Windows for Docker v3.17...
Windows-10  | ❯ For support visit https://github.com/dockur/windows
Windows-10  | ❯ CPU: AMD Ryzen 7 5700U | RAM: 26/29 GB | DISK: 76 GB (ext4) | HOST: 6.8.0-45...
Windows-10  | 
Windows-10  | [1;31m❯ Warning: unexpected clocksource: hpet[0m
Windows-10  | [1;34m❯ [1;36mBooting Windows using QEMU v9.0.2...[0m
Windows-10  | [2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01H[2J[01;01H[=3h[2J[01;01HBdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,BCF6F541-B2FA-4D61-8AD1-37CF0F177F91,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
Windows-10  | BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,BCF6F541-B2FA-4D61-8AD1-37CF0F177F91,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
Windows-10  | [1;34m❯ [1;36mWindows started succesfully, visit http://localhost:8006/ to view the screen...[0m
```
