### ISSUE TITLE
Windows cannot access \\host.lan

### ISSUE THREAD

**Issue by Mordeaux** [dockur/windows#782]
### Operating system

Ubuntu 24.04.1 LTS

### Description

Twice on two separate computers I have attempted to share a folder from my host to the container, and on both computers I have the same error (One is running Ubuntu 24.04.1 and the other 23.10, the newer one is a fresh install). 

What I am trying to do is to have my app's code shared between my host and the windows container, so that I can run a development environment that is in Windows but edit the code on my Linux host, is this even possible?

I have read through the past issues trying to find a solution, and they all either didn't work, or I didn't understand what they were saying to do. Thank you for your help!

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
    - ./shared:/shared
    - ./post-install:/oem
```

### Docker log

```
Attaching to windows                                                                                                                                                                          
windows  | ❯ Starting Windows for Docker v3.21...                                                                                                                                             
windows  | ❯ For support visit https://github.com/dockur/windows                                                                                                                              
windows  | ❯ CPU: Intel Core TM i7 8750H CPU | RAM: 10/16 GB | DISK: 228 GB (ext4) | HOST: 6.8.0-45...                                                                                        
windows  |                                                                                                                                                                                    
windows  | ❯ Booting Windows using QEMU v9.1.0...                                                                                                                                             
windows  |                                                                                                                                                                                    
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,5B016D92-CF07-4A8B-83AC-CAD689B805D6,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi                                            
windows  | BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,5B016D92-CF07-4A8B-83AC-CAD689B805D6,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
windows  | ❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
```

### Screenshots (optional)

![Screenshot from 2024-10-08 09-19-40](https://github.com/user-attachments/assets/909b0941-24a3-4858-b425-f8235c9cf190)
