### ISSUE TITLE
After copying .img and windows.* to a new location, the container fails to start

### ISSUE THREAD

**Issue by lcax200000** [dockur/windows#828]
### Operating system

ubuntu 22.04

### Description

Whenever I copy the data.img/qcow2 and windows.* files to another location and then run a new container, I always get the following error: "ERROR: Failed to start TPM emulator".
I am not sure what might be causing this issue. Could you please provide some guidance on how to resolve this problem?
Thank you!

### Docker compose

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: win
spec:
  template:
    metadata:
      labels:
        app: win
    spec:
      containers:
        - name: windows
          image: dockurr/windows:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VERSION
              value: "win10x64"
            - name: DISK_FMT
              value: "qcow2"
            - name: MANUAL
              value: "N"
            - name: TPM
              value: "N"
            - name: DEBUG
              value: "Y"
                - name: ARGUMENTS
                value: "-device vfio-pci,host=01:00.0,multifunction=on -device vfio-pci,host=01:00.1,multifunction=on -device usb-host,vendorid=0x1a2c,productid=0x6004 -device usb-host,vendorid=0x1c4f,productid=0x0034 -device virtio-mouse-pci"
            - name: RAM_SIZE
              value: "8G"
            - name: CPU_CORES
              value: "8"
            - name: DISK_SIZE
              value: "32G"
          ports:
              containerPort: 8006
              hostPort: 8006
            - protocol: UDP
              containerPort: 8006
              hostPort: 8006
          volumeMounts:
            - name: base-qcow
              mountPath: /storage
            - mountPath: /dev/kvm
              name: dev-kvm
          securityContext:
            privileged: true
      volumes:
        - name: base-qcow
          nfs:
            server: 192.168.5.71
            path: /data/disk2/base_qcow2
            readOnly: true
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
       


         

```

### Docker log

**Most of the time prompts:**

root@user-MS-7E44:/home/user/script/k8s# kubectl logs win-1-xshjp   -c windows
❯ Starting Windows for Docker v0.0...
❯ For support visit https://github.com/dockur/windows
❯ CPU: 12th Gen Intel Core TM i5 12400 | RAM: 11/16 GB | DISK: 195 GB (ext4) | HOST: 6.8.0-47...

❯ Detected that the version was changed, but ignoring this because Windows is already installed.
❯ Please start with an empty /storage folder, if you want to install a different version of Windows.
❯ Host: win-1-xshjp  IP: 10.42.0.119  Gateway: 10.42.0.1  Interface: eth0  MAC: 02:1D:D6:15:DB:8E
nameserver 10.43.0.10

swtpm: Could not open UnixIO socket: Permission denied
❯ ERROR: Failed to start TPM emulator, reason: 0

**Occasionally prompt:**
kubectl logs win-1-ks8lg  -c windows
❯ Starting Windows for Docker v0.0...
❯ For support visit https://github.com/dockur/windows
❯ CPU: 12th Gen Intel Core TM i5 12400 | RAM: 11/16 GB | DISK: 195 GB (ext4) | HOST: 6.8.0-47...

❯ Detected that the version was changed, but ignoring this because Windows is already installed.
❯ Please start with an empty /storage folder, if you want to install a different version of Windows.
❯ Host: win-1-ks8lg  IP: 10.42.0.123  Gateway: 10.42.0.1  Interface: eth0  MAC: 02:1D:D6:15:DB:8E
nameserver 10.43.0.10

RTNETLINK answers: File exists
❯ ERROR: Failed to create bridge. Please add the following setting to your container: --cap-add NET_ADMIN
❯ Warning: falling back to usermode networking! Performance will be bad and port forwarding will not work.
swtpm: Could not open UnixIO socket: Permission denied
❯ ERROR: Failed to start TPM emulator, reason: 0
