### ISSUE TITLE
You have been disconnected because another connection was made to the remote PC. 

### ISSUE THREAD

**Issue by dzavadindev** [dockur/windows#840]
### Operating system

Windows 11

### Description

When trying to connect to the container via the MS Remote Desktop, getting this error. Have the connection set up so it asks for user every time, tried both with and without specifying the port as PC name. The web UI works alright, if that maters at all. Had Remote Desktop Services disabled on host machine, turned those on, but no change.

Don't know what to add here, really. As far as I am aware, no other connections are opened at the same time I am trying to connect. Got no logs, no errors besides the ones from MSRD, connecting to the container doesn't leave any error log in docker either. If you have an idea where some useful logs can be found on the target machine, I can access it via the web interface to check.

### Docker compose

``` yaml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./data:/storage
      - ./share:/data
```

### Docker log

Nothing of interest here...

```
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,70363609-5CFC-482F-9234-5DB06D85C6B1,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,70363609-5CFC-482F-9234-5DB06D85C6B1,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
```

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/d6af17b6-3ae2-49ae-9c19-4bdbd9cfdd6c)
