### ISSUE TITLE
unable to run bluestacks

### ISSUE THREAD

**Issue by syffs** [dockur/windows#842]
### Operating system

Ubuntu 24.04

### Description

Trying to run bluestacks doesn't work and leads to this article: https://support.bluestacks.com/hc/en-us/articles/6042486534797-Troubleshooting-guide-for-BlueStacks-5

Any idea?

### Docker compose

```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    volumes:
      - /opt/dockur/win11:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```

### Docker log

```
❯ Booting Windows using QEMU v9.1.0...
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,4BFA3434-39C2-43AE-97DA-A4D4A6795145,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,4BFA3434-39C2-43AE-97DA-A4D4A6795145,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: loading Boot0004 "Windows Boot Manager" from HD(1,GPT,4BFA3434-39C2-43AE-97DA-A4D4A6795145,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0004 "Windows Boot Manager" from HD(1,GPT,4BFA3434-39C2-43AE-97DA-A4D4A6795145,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
```

### Screenshots (optional)

<img width="986" alt="image" src="https://github.com/user-attachments/assets/bdd1ad2f-b014-4b3f-ae26-e88d97b8f92e">
