### ISSUE TITLE
ERROR:target/i386/tcg/translate.c:748:gen_helper_out_func: code should not be reached

### ISSUE THREAD

**Issue by i1Fury** [dockur/windows#847]
### Operating system

Ubuntu 24.04

### Description

I couldn't get past the Windows setup wheel, so I left to see if it was just slow. I came back and the docker container was shut down.

This is running on ubuntu with no kvm instance.

### Docker compose

```yml
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      KVM: "N"  # Disable KVM acceleration
      VERSION: "win10"
      HV: "N"
      BOOT_MODE: "windows_plain"
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 8080:8080
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - /home/ecs/windows/storage:/storage
```

### Docker log

```
❯ Starting Windows for Docker v4.00...
❯ For support visit https://github.com/dockur/windows
❯ CPU: QEMU Virtual CPU version 2 5  | RAM: 14/16 GB | DISK: 57 GB (ext4) | HOST: 6.8.0-48...

❯ Booting Windows securely using QEMU v9.1.0...
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
❯ Received SIGTERM, sending ACPI shutdown signal...
❯ Cannot send ACPI signal during Windows setup, aborting...
❯ ERROR: Forcefully terminating Windows, reason: 143...
❯ Starting Windows for Docker v4.00...
❯ For support visit https://github.com/dockur/windows
❯ CPU: QEMU Virtual CPU version 2 5  | RAM: 14/16 GB | DISK: 57 GB (ext4) | HOST: 6.8.0-48...

❯ Booting Windows securely using QEMU v9.1.0...
BdsDxe: failed to load Boot0002 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0): Not Found
BdsDxe: loading Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU DVD-ROM QM00013 " from PciRoot(0x0)/Pci(0x5,0x0)/Sata(0x0,0xFFFF,0x0)
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
**
ERROR:target/i386/tcg/translate.c:748:gen_helper_out_func: code should not be reached
❯ ERROR: Forcefully terminating Windows, reason: 0...
❯ Shutdown completed!
```
