### ISSUE TITLE
[Question]: VPN connection method

### ISSUE THREAD

**Issue by jtabox** [dockur/windows#928]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/dockur/windows/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

Hi, I'm trying to connect a Dockur Windows Server 2025 container to VPN (WireGuard) with killswitch, and so far I've tried 2 methods that work (with some adjustments). But I'm not sure which one would be the most appropriate (mostly regarding security but also effectiveness).

The first method is to use another container ([Gluetun](https://github.com/qdm12/gluetun)) that connects to a VPN, and use it as Dockur's network service. I do this already from the compose file, but with some changes:
```
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped
    networks:
      - gluetun_net
    environment:
      - VARIOUS VPN PARAMS=here
      # ...
      # CIDR/IPs that Gluetun and its connected containers are allowed to access:
      - FIREWALL_OUTBOUND_SUBNETS= 10.0.0.0/16 # My LAN

  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2025"
    volumes:
      - ./storage:/storage
      - ./data:/data
    devices:
      - /dev/kvm
    restart: unless-stopped
    stop_grace_period: 2m
    depends_on:
      - gluetun
    network_mode: service:gluetun

networks:
  gluetun_net:
    name: gluetun_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1
```
So in order to be able to connect to the Dockur Windows:
* I need to move the exposed ports directive to Gluetun, otherwise they're not visible from my LAN (Docker and its containers run on one PC and I connect from another). 
* I have to remove every network-related directive from Dockur (the `cap_add` directive, `DHCP` and `MACVLAN` support).

This method works, but I think Gluetun might be exposing Dockur's RDP and VNC ports publicly too, not just towards my LAN (which doesn't feel like a good thing since I don't need it). I guess I could try and figure out what iptables commands I could tell Gluetun to run, it has this option.

The other method is to simply connect the Dockur Windows container normally (with directives for `MACVLAN` and `DHCP` in the compose file) to my LAN, and then from inside it run a WireGuard client with killswitch. But in this case I can't connect from my LAN, and the `/data` volume isn't accessible either. But if this is safer than the previous method, I guess I'll have to figure out how to configure Dockur to accept RDP connections from my LAN?

Or is there any other recommended way to connect to VPN while still accepting RDP connections from inside my LAN?
