### ISSUE TITLE
[Bug]: PASSWORD is not valid

### ISSUE THREAD

**Issue by shaxiaozz** [dockur/windows#951]
### Operating system

Ubuntu 24.04.1 LTS

### Description

I ran docker windows on ubuntu according to the README in the project. At first, I directly git cloned and then ran docker compose up -d. Therefore, the content of ***compose.yml*** is as follows:
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```

Then I visited CONTAINER_IP:8006 and found that it was already in the stage of installing windows, but I observed more content in README and found that it could be persisted, so the content of ***compose.yml*** at this time was as follows:
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ${PWD}/volumes:/storage
```

Then, after windows was installed, I wanted to connect through RDP and found that an account and password were required, but I found that I didn’t have an account and password, so I checked the README content and found that it could be set through the environment variables USERNAME and PASSWORD, so the content of ***compose.yml*** at this time was as follows:
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      USERNAME: "admin"
      PASSWORD: "admin"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - ${PWD}/volumes:/storage
```
Then I restarted the windows container through ```docker compose down && docker compose up -d```

But when I connected to RDP, I still couldn’t enter windows through admin/admin. Later, I found in issues that when installing windows unattended, an account will be created by default: Docker, password: empty. Then I entered windows through this account.

Are the environment variables USERNAME and PASSWORD configured at different times? ? I understand that this environment variable should be created when the Windows user does not exist, and ignored if the Windows user already exists.

At the same time, if the environment variables USERNAME and PASSWORD need to be configured during the first installation, should the correct instructions be given in the README? Otherwise, it should be reflected in the logs when the Windows container is not run for the first time.

### Docker compose

As above

### Docker log

````
# docker logs windows 
❯ Starting Windows for Docker v4.06...
❯ For support visit https://github.com/dockur/windows
❯ CPU: AMD EPYC 7J13 64 Core | RAM: 1663/1772 GB | DISK: 16306 GB (ext4) | KERNEL: 6.8.0-49...

❯ Warning: unexpected clocksource: kvm-clock
❯ Booting Windows securely using QEMU v9.1.1...






BdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,777F01E2-AC58-498E-8C8D-4BE8F3215424,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,777F01E2-AC58-498E-8C8D-4BE8F3215424,0x800,0x40000)/\EFI\Microsoft\Boot\bootmgfw.efi
❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...
```

### Screenshots (optional)

_No response_
