### ISSUE TITLE
[Bug]: Windows 11 24H2 can not connect to host.lan

### ISSUE THREAD

**Issue by mebtte** [dockur/windows#976]
### Operating system

Ubuntu 24.04.1 LTS

### Description

After upgrading to Windows 11 24H2, it can not connect to host.lan anymore.

### Docker compose

services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    ports:
      - 8006:8006
      - 3389:3389
    environment:
      VERSION: "11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "64G"
      MANUAL: "Y"
    devices:
      - /dev/net/tun
      - /dev/kvm
    volumes:
      - /path/storage:/storage
      - /path/data:/data

### Docker log

❯ Starting Windows for Docker v4.06...

❯ For support visit https://github.com/dockur/windows

❯ CPU: Intel Core i5 10500T | RAM: 18/24 GB | DISK: 768 GB (xfs) | KERNEL: 6.8.0-51...

❯ Detected that the version was changed, but ignoring this because Windows is already installed.

❯ Please start with an empty /storage folder, if you want to install a different version of Windows.

❯ Booting Windows securely using QEMU v9.1.1...

3h3h3hBdsDxe: loading Boot0003 "Windows Boot Manager" from HD(1,GPT,B5F6E3A3-44CE-446F-8798-CFA81529889F,0x800,0x32000)/\EFI\Microsoft\Boot\bootmgfw.efi

BdsDxe: starting Boot0003 "Windows Boot Manager" from HD(1,GPT,B5F6E3A3-44CE-446F-8798-CFA81529889F,0x800,0x32000)/\EFI\Microsoft\Boot\bootmgfw.efi

❯ Windows started succesfully, visit http://localhost:8006/ to view the screen...

**Comment by PaarXul** [comment]
try adding this line in your docker compose

`    privileged: true
`

EXAMPLE
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    privileged: true
    environment:
      VERSION: "win10"  
      LANGUAGE: "English"
      REGION: "en-ES"
      KEYBOARD: "en-ES"
      DISK_SIZE: "80G"
      RAM_SIZE: "10G"
      CPU_CORES: "6"
      USERNAME: "nameuser"
      PASSWORD: "password"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
    volumes:
      - /home/user/Desktop/WINDOWS:/shared
      - ./data:/storage
```
