### ISSUE TITLE
Permission Denied - /storage/tmp

### ISSUE THREAD

**Issue by deathblade666** [dockur/windows#998]
### Operating system

Fedora 41

### Description

If i try to add a volume that maps to storage i get permissions errors. I've even tried changing permissions on the folder on the host to ``777``.

### Docker compose
```
services:
  windows:
    image: dockurr/windows
    container_name: windows
    volumes:
      - /opt/windows:/storage
    environment:
      RAM_SIZE: "8GB"
      CPU_CORES: "4"
      DISK_SIZE: "100G"
      VERSION: "11"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
```

### Docker log
```
windows  | mkdir: cannot create directory '/storage/tmp': Permission denied
windows  | ❯ Requesting Windows 11 from Microsoft server...
windows  | ❯ ERROR: Failed to contact Microsoft servers! Is there an Internet connection or is the server down?
windows  | ❯ Failed to download Windows 11, will try a diferent method now...
windows  | ❯ Downloading product information from Microsoft server...
windows  | mkdir: cannot create directory '/storage/tmp': Permission denied
windows  | /storage/tmp/esd/catalog.cab: No such file or directory
windows  | ❯ ERROR: Failed to download https://go.microsoft.com/fwlink?linkid=2156292 , reason: 1
windows  | ❯ Failed to download Windows 11, will try another mirror now...
windows  | df: /storage/tmp: No such file or directory
windows  | ❯ ERROR: Not enough free space left to download file!
windows exited with code 61
```
